/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../people-body/hand-fingers-closed';
     
export const EMOJI_LIST = [
  { emoji: Emojis.HandFingersClosed1, name: 'HandFingersClosed1' },
  { emoji: Emojis.HandFingersClosed10, name: 'HandFingersClosed10' },
  { emoji: Emojis.HandFingersClosed11, name: 'HandFingersClosed11' },
  { emoji: Emojis.HandFingersClosed12, name: 'HandFingersClosed12' },
  { emoji: Emojis.HandFingersClosed13, name: 'HandFingersClosed13' },
  { emoji: Emojis.HandFingersClosed14, name: 'HandFingersClosed14' },
  { emoji: Emojis.HandFingersClosed15, name: 'HandFingersClosed15' },
  { emoji: Emojis.HandFingersClosed16, name: 'HandFingersClosed16' },
  { emoji: Emojis.HandFingersClosed17, name: 'HandFingersClosed17' },
  { emoji: Emojis.HandFingersClosed18, name: 'HandFingersClosed18' },
  { emoji: Emojis.HandFingersClosed19, name: 'HandFingersClosed19' },
  { emoji: Emojis.HandFingersClosed2, name: 'HandFingersClosed2' },
  { emoji: Emojis.HandFingersClosed20, name: 'HandFingersClosed20' },
  { emoji: Emojis.HandFingersClosed21, name: 'HandFingersClosed21' },
  { emoji: Emojis.HandFingersClosed22, name: 'HandFingersClosed22' },
  { emoji: Emojis.HandFingersClosed23, name: 'HandFingersClosed23' },
  { emoji: Emojis.HandFingersClosed24, name: 'HandFingersClosed24' },
  { emoji: Emojis.HandFingersClosed25, name: 'HandFingersClosed25' },
  { emoji: Emojis.HandFingersClosed26, name: 'HandFingersClosed26' },
  { emoji: Emojis.HandFingersClosed27, name: 'HandFingersClosed27' },
  { emoji: Emojis.HandFingersClosed28, name: 'HandFingersClosed28' },
  { emoji: Emojis.HandFingersClosed29, name: 'HandFingersClosed29' },
  { emoji: Emojis.HandFingersClosed3, name: 'HandFingersClosed3' },
  { emoji: Emojis.HandFingersClosed30, name: 'HandFingersClosed30' },
  { emoji: Emojis.HandFingersClosed31, name: 'HandFingersClosed31' },
  { emoji: Emojis.HandFingersClosed32, name: 'HandFingersClosed32' },
  { emoji: Emojis.HandFingersClosed33, name: 'HandFingersClosed33' },
  { emoji: Emojis.HandFingersClosed34, name: 'HandFingersClosed34' },
  { emoji: Emojis.HandFingersClosed35, name: 'HandFingersClosed35' },
  { emoji: Emojis.HandFingersClosed36, name: 'HandFingersClosed36' },
  { emoji: Emojis.HandFingersClosed4, name: 'HandFingersClosed4' },
  { emoji: Emojis.HandFingersClosed5, name: 'HandFingersClosed5' },
  { emoji: Emojis.HandFingersClosed6, name: 'HandFingersClosed6' },
  { emoji: Emojis.HandFingersClosed7, name: 'HandFingersClosed7' },
  { emoji: Emojis.HandFingersClosed8, name: 'HandFingersClosed8' },
  { emoji: Emojis.HandFingersClosed9, name: 'HandFingersClosed9' },
];
  