/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../people-body/hand-fingers-partial';
     
export const EMOJI_LIST = [
  { emoji: Emojis.HandFingersPartial1, name: 'HandFingersPartial1' },
  { emoji: Emojis.HandFingersPartial10, name: 'HandFingersPartial10' },
  { emoji: Emojis.HandFingersPartial11, name: 'HandFingersPartial11' },
  { emoji: Emojis.HandFingersPartial12, name: 'HandFingersPartial12' },
  { emoji: Emojis.HandFingersPartial13, name: 'HandFingersPartial13' },
  { emoji: Emojis.HandFingersPartial14, name: 'HandFingersPartial14' },
  { emoji: Emojis.HandFingersPartial15, name: 'HandFingersPartial15' },
  { emoji: Emojis.HandFingersPartial16, name: 'HandFingersPartial16' },
  { emoji: Emojis.HandFingersPartial17, name: 'HandFingersPartial17' },
  { emoji: Emojis.HandFingersPartial18, name: 'HandFingersPartial18' },
  { emoji: Emojis.HandFingersPartial19, name: 'HandFingersPartial19' },
  { emoji: Emojis.HandFingersPartial2, name: 'HandFingersPartial2' },
  { emoji: Emojis.HandFingersPartial20, name: 'HandFingersPartial20' },
  { emoji: Emojis.HandFingersPartial21, name: 'HandFingersPartial21' },
  { emoji: Emojis.HandFingersPartial22, name: 'HandFingersPartial22' },
  { emoji: Emojis.HandFingersPartial23, name: 'HandFingersPartial23' },
  { emoji: Emojis.HandFingersPartial24, name: 'HandFingersPartial24' },
  { emoji: Emojis.HandFingersPartial25, name: 'HandFingersPartial25' },
  { emoji: Emojis.HandFingersPartial26, name: 'HandFingersPartial26' },
  { emoji: Emojis.HandFingersPartial27, name: 'HandFingersPartial27' },
  { emoji: Emojis.HandFingersPartial28, name: 'HandFingersPartial28' },
  { emoji: Emojis.HandFingersPartial29, name: 'HandFingersPartial29' },
  { emoji: Emojis.HandFingersPartial3, name: 'HandFingersPartial3' },
  { emoji: Emojis.HandFingersPartial30, name: 'HandFingersPartial30' },
  { emoji: Emojis.HandFingersPartial31, name: 'HandFingersPartial31' },
  { emoji: Emojis.HandFingersPartial32, name: 'HandFingersPartial32' },
  { emoji: Emojis.HandFingersPartial33, name: 'HandFingersPartial33' },
  { emoji: Emojis.HandFingersPartial34, name: 'HandFingersPartial34' },
  { emoji: Emojis.HandFingersPartial35, name: 'HandFingersPartial35' },
  { emoji: Emojis.HandFingersPartial36, name: 'HandFingersPartial36' },
  { emoji: Emojis.HandFingersPartial37, name: 'HandFingersPartial37' },
  { emoji: Emojis.HandFingersPartial38, name: 'HandFingersPartial38' },
  { emoji: Emojis.HandFingersPartial39, name: 'HandFingersPartial39' },
  { emoji: Emojis.HandFingersPartial4, name: 'HandFingersPartial4' },
  { emoji: Emojis.HandFingersPartial40, name: 'HandFingersPartial40' },
  { emoji: Emojis.HandFingersPartial41, name: 'HandFingersPartial41' },
  { emoji: Emojis.HandFingersPartial42, name: 'HandFingersPartial42' },
  { emoji: Emojis.HandFingersPartial5, name: 'HandFingersPartial5' },
  { emoji: Emojis.HandFingersPartial6, name: 'HandFingersPartial6' },
  { emoji: Emojis.HandFingersPartial7, name: 'HandFingersPartial7' },
  { emoji: Emojis.HandFingersPartial8, name: 'HandFingersPartial8' },
  { emoji: Emojis.HandFingersPartial9, name: 'HandFingersPartial9' },
];
  