/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../people-body/hand-fingers-open';

export const EMOJI_LIST = [
  { emoji: Emojis.HandFingersOpen1, name: 'HandFingersOpen1' },
  { emoji: Emojis.HandFingersOpen10, name: 'HandFingersOpen10' },
  { emoji: Emojis.HandFingersOpen11, name: 'HandFingersOpen11' },
  { emoji: Emojis.HandFingersOpen12, name: 'HandFingersOpen12' },
  { emoji: Emojis.HandFingersOpen13, name: 'HandFingersOpen13' },
  { emoji: Emojis.HandFingersOpen14, name: 'HandFingersOpen14' },
  { emoji: Emojis.HandFingersOpen15, name: 'HandFingersOpen15' },
  { emoji: Emojis.HandFingersOpen16, name: 'HandFingersOpen16' },
  { emoji: Emojis.HandFingersOpen17, name: 'HandFingersOpen17' },
  { emoji: Emojis.HandFingersOpen18, name: 'HandFingersOpen18' },
  { emoji: Emojis.HandFingersOpen19, name: 'HandFingersOpen19' },
  { emoji: Emojis.HandFingersOpen2, name: 'HandFingersOpen2' },
  { emoji: Emojis.HandFingersOpen20, name: 'HandFingersOpen20' },
  { emoji: Emojis.HandFingersOpen21, name: 'HandFingersOpen21' },
  { emoji: Emojis.HandFingersOpen22, name: 'HandFingersOpen22' },
  { emoji: Emojis.HandFingersOpen23, name: 'HandFingersOpen23' },
  { emoji: Emojis.HandFingersOpen24, name: 'HandFingersOpen24' },
  { emoji: Emojis.HandFingersOpen25, name: 'HandFingersOpen25' },
  { emoji: Emojis.HandFingersOpen26, name: 'HandFingersOpen26' },
  { emoji: Emojis.HandFingersOpen27, name: 'HandFingersOpen27' },
  { emoji: Emojis.HandFingersOpen28, name: 'HandFingersOpen28' },
  { emoji: Emojis.HandFingersOpen29, name: 'HandFingersOpen29' },
  { emoji: Emojis.HandFingersOpen3, name: 'HandFingersOpen3' },
  { emoji: Emojis.HandFingersOpen30, name: 'HandFingersOpen30' },
  { emoji: Emojis.HandFingersOpen4, name: 'HandFingersOpen4' },
  { emoji: Emojis.HandFingersOpen5, name: 'HandFingersOpen5' },
  { emoji: Emojis.HandFingersOpen6, name: 'HandFingersOpen6' },
  { emoji: Emojis.HandFingersOpen7, name: 'HandFingersOpen7' },
  { emoji: Emojis.HandFingersOpen8, name: 'HandFingersOpen8' },
  { emoji: Emojis.HandFingersOpen9, name: 'HandFingersOpen9' },
];
  