/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../people-body/hand-prop';
     
export const EMOJI_LIST = [
  { emoji: Emojis.HandProp1, name: 'HandProp1' },
  { emoji: Emojis.HandProp10, name: 'HandProp10' },
  { emoji: Emojis.HandProp11, name: 'HandProp11' },
  { emoji: Emojis.HandProp12, name: 'HandProp12' },
  { emoji: Emojis.HandProp13, name: 'HandProp13' },
  { emoji: Emojis.HandProp14, name: 'HandProp14' },
  { emoji: Emojis.HandProp15, name: 'HandProp15' },
  { emoji: Emojis.HandProp16, name: 'HandProp16' },
  { emoji: Emojis.HandProp17, name: 'HandProp17' },
  { emoji: Emojis.HandProp18, name: 'HandProp18' },
  { emoji: Emojis.HandProp2, name: 'HandProp2' },
  { emoji: Emojis.HandProp3, name: 'HandProp3' },
  { emoji: Emojis.HandProp4, name: 'HandProp4' },
  { emoji: Emojis.HandProp5, name: 'HandProp5' },
  { emoji: Emojis.HandProp6, name: 'HandProp6' },
  { emoji: Emojis.HandProp7, name: 'HandProp7' },
  { emoji: Emojis.HandProp8, name: 'HandProp8' },
  { emoji: Emojis.HandProp9, name: 'HandProp9' },
];
  