/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../people-body/hand-single-finger';
     
export const EMOJI_LIST = [
  { emoji: Emojis.HandSingleFinger1, name: 'HandSingleFinger1' },
  { emoji: Emojis.HandSingleFinger10, name: 'HandSingleFinger10' },
  { emoji: Emojis.HandSingleFinger11, name: 'HandSingleFinger11' },
  { emoji: Emojis.HandSingleFinger12, name: 'HandSingleFinger12' },
  { emoji: Emojis.HandSingleFinger13, name: 'HandSingleFinger13' },
  { emoji: Emojis.HandSingleFinger14, name: 'HandSingleFinger14' },
  { emoji: Emojis.HandSingleFinger15, name: 'HandSingleFinger15' },
  { emoji: Emojis.HandSingleFinger16, name: 'HandSingleFinger16' },
  { emoji: Emojis.HandSingleFinger17, name: 'HandSingleFinger17' },
  { emoji: Emojis.HandSingleFinger18, name: 'HandSingleFinger18' },
  { emoji: Emojis.HandSingleFinger19, name: 'HandSingleFinger19' },
  { emoji: Emojis.HandSingleFinger2, name: 'HandSingleFinger2' },
  { emoji: Emojis.HandSingleFinger20, name: 'HandSingleFinger20' },
  { emoji: Emojis.HandSingleFinger21, name: 'HandSingleFinger21' },
  { emoji: Emojis.HandSingleFinger22, name: 'HandSingleFinger22' },
  { emoji: Emojis.HandSingleFinger23, name: 'HandSingleFinger23' },
  { emoji: Emojis.HandSingleFinger24, name: 'HandSingleFinger24' },
  { emoji: Emojis.HandSingleFinger25, name: 'HandSingleFinger25' },
  { emoji: Emojis.HandSingleFinger26, name: 'HandSingleFinger26' },
  { emoji: Emojis.HandSingleFinger27, name: 'HandSingleFinger27' },
  { emoji: Emojis.HandSingleFinger28, name: 'HandSingleFinger28' },
  { emoji: Emojis.HandSingleFinger29, name: 'HandSingleFinger29' },
  { emoji: Emojis.HandSingleFinger3, name: 'HandSingleFinger3' },
  { emoji: Emojis.HandSingleFinger30, name: 'HandSingleFinger30' },
  { emoji: Emojis.HandSingleFinger31, name: 'HandSingleFinger31' },
  { emoji: Emojis.HandSingleFinger32, name: 'HandSingleFinger32' },
  { emoji: Emojis.HandSingleFinger33, name: 'HandSingleFinger33' },
  { emoji: Emojis.HandSingleFinger34, name: 'HandSingleFinger34' },
  { emoji: Emojis.HandSingleFinger35, name: 'HandSingleFinger35' },
  { emoji: Emojis.HandSingleFinger36, name: 'HandSingleFinger36' },
  { emoji: Emojis.HandSingleFinger4, name: 'HandSingleFinger4' },
  { emoji: Emojis.HandSingleFinger5, name: 'HandSingleFinger5' },
  { emoji: Emojis.HandSingleFinger6, name: 'HandSingleFinger6' },
  { emoji: Emojis.HandSingleFinger7, name: 'HandSingleFinger7' },
  { emoji: Emojis.HandSingleFinger8, name: 'HandSingleFinger8' },
  { emoji: Emojis.HandSingleFinger9, name: 'HandSingleFinger9' },
];
  