/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../people-body/hands';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Hands1, name: 'Hands1' },
  { emoji: Emojis.Hands10, name: 'Hands10' },
  { emoji: Emojis.Hands11, name: 'Hands11' },
  { emoji: Emojis.Hands12, name: 'Hands12' },
  { emoji: Emojis.Hands13, name: 'Hands13' },
  { emoji: Emojis.Hands14, name: 'Hands14' },
  { emoji: Emojis.Hands15, name: 'Hands15' },
  { emoji: Emojis.Hands16, name: 'Hands16' },
  { emoji: Emojis.Hands17, name: 'Hands17' },
  { emoji: Emojis.Hands18, name: 'Hands18' },
  { emoji: Emojis.Hands19, name: 'Hands19' },
  { emoji: Emojis.Hands2, name: 'Hands2' },
  { emoji: Emojis.Hands20, name: 'Hands20' },
  { emoji: Emojis.Hands21, name: 'Hands21' },
  { emoji: Emojis.Hands22, name: 'Hands22' },
  { emoji: Emojis.Hands23, name: 'Hands23' },
  { emoji: Emojis.Hands24, name: 'Hands24' },
  { emoji: Emojis.Hands25, name: 'Hands25' },
  { emoji: Emojis.Hands26, name: 'Hands26' },
  { emoji: Emojis.Hands27, name: 'Hands27' },
  { emoji: Emojis.Hands28, name: 'Hands28' },
  { emoji: Emojis.Hands29, name: 'Hands29' },
  { emoji: Emojis.Hands3, name: 'Hands3' },
  { emoji: Emojis.Hands30, name: 'Hands30' },
  { emoji: Emojis.Hands31, name: 'Hands31' },
  { emoji: Emojis.Hands4, name: 'Hands4' },
  { emoji: Emojis.Hands5, name: 'Hands5' },
  { emoji: Emojis.Hands6, name: 'Hands6' },
  { emoji: Emojis.Hands7, name: 'Hands7' },
  { emoji: Emojis.Hands8, name: 'Hands8' },
  { emoji: Emojis.Hands9, name: 'Hands9' },
];
  