/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../people-body/person-resting';

export const EMOJI_LIST = [
  { emoji: Emojis.PersonResting1, name: 'PersonResting1' },
  { emoji: Emojis.PersonResting10, name: 'PersonResting10' },
  { emoji: Emojis.PersonResting11, name: 'PersonResting11' },
  { emoji: Emojis.PersonResting12, name: 'PersonResting12' },
  { emoji: Emojis.PersonResting13, name: 'PersonResting13' },
  { emoji: Emojis.PersonResting14, name: 'PersonResting14' },
  { emoji: Emojis.PersonResting15, name: 'PersonResting15' },
  { emoji: Emojis.PersonResting16, name: 'PersonResting16' },
  { emoji: Emojis.PersonResting17, name: 'PersonResting17' },
  { emoji: Emojis.PersonResting18, name: 'PersonResting18' },
  { emoji: Emojis.PersonResting19, name: 'PersonResting19' },
  { emoji: Emojis.PersonResting2, name: 'PersonResting2' },
  { emoji: Emojis.PersonResting20, name: 'PersonResting20' },
  { emoji: Emojis.PersonResting21, name: 'PersonResting21' },
  { emoji: Emojis.PersonResting22, name: 'PersonResting22' },
  { emoji: Emojis.PersonResting23, name: 'PersonResting23' },
  { emoji: Emojis.PersonResting24, name: 'PersonResting24' },
  { emoji: Emojis.PersonResting25, name: 'PersonResting25' },
  { emoji: Emojis.PersonResting26, name: 'PersonResting26' },
  { emoji: Emojis.PersonResting27, name: 'PersonResting27' },
  { emoji: Emojis.PersonResting28, name: 'PersonResting28' },
  { emoji: Emojis.PersonResting29, name: 'PersonResting29' },
  { emoji: Emojis.PersonResting3, name: 'PersonResting3' },
  { emoji: Emojis.PersonResting30, name: 'PersonResting30' },
  { emoji: Emojis.PersonResting4, name: 'PersonResting4' },
  { emoji: Emojis.PersonResting5, name: 'PersonResting5' },
  { emoji: Emojis.PersonResting6, name: 'PersonResting6' },
  { emoji: Emojis.PersonResting7, name: 'PersonResting7' },
  { emoji: Emojis.PersonResting8, name: 'PersonResting8' },
  { emoji: Emojis.PersonResting9, name: 'PersonResting9' },
];
  