/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../people-body/person-symbol';
     
export const EMOJI_LIST = [
  { emoji: Emojis.PersonSymbol1, name: 'PersonSymbol1' },
  { emoji: Emojis.PersonSymbol2, name: 'PersonSymbol2' },
  { emoji: Emojis.PersonSymbol3, name: 'PersonSymbol3' },
  { emoji: Emojis.PersonSymbol4, name: 'PersonSymbol4' },
  { emoji: Emojis.PersonSymbol5, name: 'PersonSymbol5' },
];
  