/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../smileys-emotion/cat-face';

export const EMOJI_LIST = [
  { emoji: Emojis.CatFace1, name: 'CatFace1' },
  { emoji: Emojis.CatFace2, name: 'CatFace2' },
  { emoji: Emojis.CatFace3, name: 'CatFace3' },
  { emoji: Emojis.CatFace4, name: 'CatFace4' },
  { emoji: Emojis.CatFace5, name: 'CatFace5' },
  { emoji: Emojis.CatFace6, name: 'CatFace6' },
  { emoji: Emojis.CatFace7, name: 'CatFace7' },
  { emoji: Emojis.CatFace8, name: 'CatFace8' },
  { emoji: Emojis.CatFace9, name: 'CatFace9' },
];
  