/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/emotion';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Emotion1, name: 'Emotion1' },
  { emoji: Emojis.Emotion10, name: 'Emotion10' },
  { emoji: Emojis.Emotion11, name: 'Emotion11' },
  { emoji: Emojis.Emotion12, name: 'Emotion12' },
  { emoji: Emojis.Emotion13, name: 'Emotion13' },
  { emoji: Emojis.Emotion14, name: 'Emotion14' },
  { emoji: Emojis.Emotion15, name: 'Emotion15' },
  { emoji: Emojis.Emotion16, name: 'Emotion16' },
  { emoji: Emojis.Emotion17, name: 'Emotion17' },
  { emoji: Emojis.Emotion18, name: 'Emotion18' },
  { emoji: Emojis.Emotion19, name: 'Emotion19' },
  { emoji: Emojis.Emotion2, name: 'Emotion2' },
  { emoji: Emojis.Emotion20, name: 'Emotion20' },
  { emoji: Emojis.Emotion21, name: 'Emotion21' },
  { emoji: Emojis.Emotion22, name: 'Emotion22' },
  { emoji: Emojis.Emotion23, name: 'Emotion23' },
  { emoji: Emojis.Emotion24, name: 'Emotion24' },
  { emoji: Emojis.Emotion25, name: 'Emotion25' },
  { emoji: Emojis.Emotion26, name: 'Emotion26' },
  { emoji: Emojis.Emotion27, name: 'Emotion27' },
  { emoji: Emojis.Emotion28, name: 'Emotion28' },
  { emoji: Emojis.Emotion29, name: 'Emotion29' },
  { emoji: Emojis.Emotion3, name: 'Emotion3' },
  { emoji: Emojis.Emotion30, name: 'Emotion30' },
  { emoji: Emojis.Emotion31, name: 'Emotion31' },
  { emoji: Emojis.Emotion32, name: 'Emotion32' },
  { emoji: Emojis.Emotion33, name: 'Emotion33' },
  { emoji: Emojis.Emotion34, name: 'Emotion34' },
  { emoji: Emojis.Emotion35, name: 'Emotion35' },
  { emoji: Emojis.Emotion4, name: 'Emotion4' },
  { emoji: Emojis.Emotion5, name: 'Emotion5' },
  { emoji: Emojis.Emotion6, name: 'Emotion6' },
  { emoji: Emojis.Emotion7, name: 'Emotion7' },
  { emoji: Emojis.Emotion8, name: 'Emotion8' },
  { emoji: Emojis.Emotion9, name: 'Emotion9' },
];
  