/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/face-hat';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FaceHat1, name: 'FaceHat1' },
  { emoji: Emojis.FaceHat2, name: 'FaceHat2' },
  { emoji: Emojis.FaceHat3, name: 'FaceHat3' },
];
  