/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/face-concerned';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FaceConcerned1, name: 'FaceConcerned1' },
  { emoji: Emojis.FaceConcerned10, name: 'FaceConcerned10' },
  { emoji: Emojis.FaceConcerned11, name: 'FaceConcerned11' },
  { emoji: Emojis.FaceConcerned12, name: 'FaceConcerned12' },
  { emoji: Emojis.FaceConcerned13, name: 'FaceConcerned13' },
  { emoji: Emojis.FaceConcerned14, name: 'FaceConcerned14' },
  { emoji: Emojis.FaceConcerned15, name: 'FaceConcerned15' },
  { emoji: Emojis.FaceConcerned16, name: 'FaceConcerned16' },
  { emoji: Emojis.FaceConcerned17, name: 'FaceConcerned17' },
  { emoji: Emojis.FaceConcerned18, name: 'FaceConcerned18' },
  { emoji: Emojis.FaceConcerned19, name: 'FaceConcerned19' },
  { emoji: Emojis.FaceConcerned2, name: 'FaceConcerned2' },
  { emoji: Emojis.FaceConcerned20, name: 'FaceConcerned20' },
  { emoji: Emojis.FaceConcerned21, name: 'FaceConcerned21' },
  { emoji: Emojis.FaceConcerned22, name: 'FaceConcerned22' },
  { emoji: Emojis.FaceConcerned23, name: 'FaceConcerned23' },
  { emoji: Emojis.FaceConcerned24, name: 'FaceConcerned24' },
  { emoji: Emojis.FaceConcerned3, name: 'FaceConcerned3' },
  { emoji: Emojis.FaceConcerned4, name: 'FaceConcerned4' },
  { emoji: Emojis.FaceConcerned5, name: 'FaceConcerned5' },
  { emoji: Emojis.FaceConcerned6, name: 'FaceConcerned6' },
  { emoji: Emojis.FaceConcerned7, name: 'FaceConcerned7' },
  { emoji: Emojis.FaceConcerned8, name: 'FaceConcerned8' },
  { emoji: Emojis.FaceConcerned9, name: 'FaceConcerned9' },
];
  