/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/face-tongue';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FaceTongue1, name: 'FaceTongue1' },
  { emoji: Emojis.FaceTongue2, name: 'FaceTongue2' },
  { emoji: Emojis.FaceTongue3, name: 'FaceTongue3' },
  { emoji: Emojis.FaceTongue4, name: 'FaceTongue4' },
  { emoji: Emojis.FaceTongue5, name: 'FaceTongue5' },
  { emoji: Emojis.FaceTongue6, name: 'FaceTongue6' },
];
  