/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/face-neutral-skeptical';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FaceNeutralSkeptical1, name: 'FaceNeutralSkeptical1' },
  { emoji: Emojis.FaceNeutralSkeptical10, name: 'FaceNeutralSkeptical10' },
  { emoji: Emojis.FaceNeutralSkeptical2, name: 'FaceNeutralSkeptical2' },
  { emoji: Emojis.FaceNeutralSkeptical3, name: 'FaceNeutralSkeptical3' },
  { emoji: Emojis.FaceNeutralSkeptical4, name: 'FaceNeutralSkeptical4' },
  { emoji: Emojis.FaceNeutralSkeptical5, name: 'FaceNeutralSkeptical5' },
  { emoji: Emojis.FaceNeutralSkeptical6, name: 'FaceNeutralSkeptical6' },
  { emoji: Emojis.FaceNeutralSkeptical7, name: 'FaceNeutralSkeptical7' },
  { emoji: Emojis.FaceNeutralSkeptical8, name: 'FaceNeutralSkeptical8' },
  { emoji: Emojis.FaceNeutralSkeptical9, name: 'FaceNeutralSkeptical9' },
];
  