/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/face-hand';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FaceHand1, name: 'FaceHand1' },
  { emoji: Emojis.FaceHand2, name: 'FaceHand2' },
  { emoji: Emojis.FaceHand3, name: 'FaceHand3' },
  { emoji: Emojis.FaceHand4, name: 'FaceHand4' },
];
  