/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/face-sleepy';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FaceSleepy1, name: 'FaceSleepy1' },
  { emoji: Emojis.FaceSleepy2, name: 'FaceSleepy2' },
  { emoji: Emojis.FaceSleepy3, name: 'FaceSleepy3' },
  { emoji: Emojis.FaceSleepy4, name: 'FaceSleepy4' },
  { emoji: Emojis.FaceSleepy5, name: 'FaceSleepy5' },
];
  