/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../smileys-emotion/face-costume';

export const EMOJI_LIST = [
  { emoji: Emojis.FaceCostume1, name: 'FaceCostume1' },
  { emoji: Emojis.FaceCostume2, name: 'FaceCostume2' },
  { emoji: Emojis.FaceCostume3, name: 'FaceCostume3' },
  { emoji: Emojis.FaceCostume4, name: 'FaceCostume4' },
  { emoji: Emojis.FaceCostume5, name: 'FaceCostume5' },
  { emoji: Emojis.FaceCostume6, name: 'FaceCostume6' },
  { emoji: Emojis.FaceCostume7, name: 'FaceCostume7' },
  { emoji: Emojis.FaceCostume8, name: 'FaceCostume8' },
];
  