/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/face-glasses';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FaceGlasses1, name: 'FaceGlasses1' },
  { emoji: Emojis.FaceGlasses2, name: 'FaceGlasses2' },
  { emoji: Emojis.FaceGlasses3, name: 'FaceGlasses3' },
];
  