/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/face-smiling';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FaceSmiling1, name: 'FaceSmiling1' },
  { emoji: Emojis.FaceSmiling10, name: 'FaceSmiling10' },
  { emoji: Emojis.FaceSmiling11, name: 'FaceSmiling11' },
  { emoji: Emojis.FaceSmiling12, name: 'FaceSmiling12' },
  { emoji: Emojis.FaceSmiling13, name: 'FaceSmiling13' },
  { emoji: Emojis.FaceSmiling2, name: 'FaceSmiling2' },
  { emoji: Emojis.FaceSmiling3, name: 'FaceSmiling3' },
  { emoji: Emojis.FaceSmiling4, name: 'FaceSmiling4' },
  { emoji: Emojis.FaceSmiling5, name: 'FaceSmiling5' },
  { emoji: Emojis.FaceSmiling6, name: 'FaceSmiling6' },
  { emoji: Emojis.FaceSmiling7, name: 'FaceSmiling7' },
  { emoji: Emojis.FaceSmiling8, name: 'FaceSmiling8' },
  { emoji: Emojis.FaceSmiling9, name: 'FaceSmiling9' },
];
  