/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/face-affection';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FaceAffection1, name: 'FaceAffection1' },
  { emoji: Emojis.FaceAffection2, name: 'FaceAffection2' },
  { emoji: Emojis.FaceAffection3, name: 'FaceAffection3' },
  { emoji: Emojis.FaceAffection4, name: 'FaceAffection4' },
  { emoji: Emojis.FaceAffection5, name: 'FaceAffection5' },
  { emoji: Emojis.FaceAffection6, name: 'FaceAffection6' },
  { emoji: Emojis.FaceAffection7, name: 'FaceAffection7' },
  { emoji: Emojis.FaceAffection8, name: 'FaceAffection8' },
  { emoji: Emojis.FaceAffection9, name: 'FaceAffection9' },
];
  