/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/face-negative';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FaceNegative1, name: 'FaceNegative1' },
  { emoji: Emojis.FaceNegative2, name: 'FaceNegative2' },
  { emoji: Emojis.FaceNegative3, name: 'FaceNegative3' },
  { emoji: Emojis.FaceNegative4, name: 'FaceNegative4' },
  { emoji: Emojis.FaceNegative5, name: 'FaceNegative5' },
  { emoji: Emojis.FaceNegative6, name: 'FaceNegative6' },
  { emoji: Emojis.FaceNegative7, name: 'FaceNegative7' },
  { emoji: Emojis.FaceNegative8, name: 'FaceNegative8' },
];
  