/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../smileys-emotion/face-unwell';

export const EMOJI_LIST = [
  { emoji: Emojis.FaceUnwell1, name: 'FaceUnwell1' },
  { emoji: Emojis.FaceUnwell10, name: 'FaceUnwell10' },
  { emoji: Emojis.FaceUnwell11, name: 'FaceUnwell11' },
  { emoji: Emojis.FaceUnwell2, name: 'FaceUnwell2' },
  { emoji: Emojis.FaceUnwell3, name: 'FaceUnwell3' },
  { emoji: Emojis.FaceUnwell4, name: 'FaceUnwell4' },
  { emoji: Emojis.FaceUnwell5, name: 'FaceUnwell5' },
  { emoji: Emojis.FaceUnwell6, name: 'FaceUnwell6' },
  { emoji: Emojis.FaceUnwell7, name: 'FaceUnwell7' },
  { emoji: Emojis.FaceUnwell8, name: 'FaceUnwell8' },
  { emoji: Emojis.FaceUnwell9, name: 'FaceUnwell9' },
];
  