/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../smileys-emotion/monkey-face';
     
export const EMOJI_LIST = [
  { emoji: Emojis.MonkeyFace1, name: 'MonkeyFace1' },
  { emoji: Emojis.MonkeyFace2, name: 'MonkeyFace2' },
  { emoji: Emojis.MonkeyFace3, name: 'MonkeyFace3' },
];
  