export { default as AwardMedal1 } from './AwardMedal1'
export { default as AwardMedal2 } from './AwardMedal2'
export { default as AwardMedal3 } from './AwardMedal3'
export { default as AwardMedal4 } from './AwardMedal4'
export { default as AwardMedal5 } from './AwardMedal5'
export { default as AwardMedal6 } from './AwardMedal6'