/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../symbols/alphanum';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Alphanum1, name: 'Alphanum1' },
  { emoji: Emojis.Alphanum10, name: 'Alphanum10' },
  { emoji: Emojis.Alphanum11, name: 'Alphanum11' },
  { emoji: Emojis.Alphanum12, name: 'Alphanum12' },
  { emoji: Emojis.Alphanum13, name: 'Alphanum13' },
  { emoji: Emojis.Alphanum14, name: 'Alphanum14' },
  { emoji: Emojis.Alphanum15, name: 'Alphanum15' },
  { emoji: Emojis.Alphanum16, name: 'Alphanum16' },
  { emoji: Emojis.Alphanum17, name: 'Alphanum17' },
  { emoji: Emojis.Alphanum18, name: 'Alphanum18' },
  { emoji: Emojis.Alphanum19, name: 'Alphanum19' },
  { emoji: Emojis.Alphanum2, name: 'Alphanum2' },
  { emoji: Emojis.Alphanum20, name: 'Alphanum20' },
  { emoji: Emojis.Alphanum21, name: 'Alphanum21' },
  { emoji: Emojis.Alphanum22, name: 'Alphanum22' },
  { emoji: Emojis.Alphanum23, name: 'Alphanum23' },
  { emoji: Emojis.Alphanum24, name: 'Alphanum24' },
  { emoji: Emojis.Alphanum25, name: 'Alphanum25' },
  { emoji: Emojis.Alphanum26, name: 'Alphanum26' },
  { emoji: Emojis.Alphanum27, name: 'Alphanum27' },
  { emoji: Emojis.Alphanum28, name: 'Alphanum28' },
  { emoji: Emojis.Alphanum29, name: 'Alphanum29' },
  { emoji: Emojis.Alphanum3, name: 'Alphanum3' },
  { emoji: Emojis.Alphanum30, name: 'Alphanum30' },
  { emoji: Emojis.Alphanum31, name: 'Alphanum31' },
  { emoji: Emojis.Alphanum32, name: 'Alphanum32' },
  { emoji: Emojis.Alphanum33, name: 'Alphanum33' },
  { emoji: Emojis.Alphanum34, name: 'Alphanum34' },
  { emoji: Emojis.Alphanum35, name: 'Alphanum35' },
  { emoji: Emojis.Alphanum36, name: 'Alphanum36' },
  { emoji: Emojis.Alphanum37, name: 'Alphanum37' },
  { emoji: Emojis.Alphanum38, name: 'Alphanum38' },
  { emoji: Emojis.Alphanum39, name: 'Alphanum39' },
  { emoji: Emojis.Alphanum4, name: 'Alphanum4' },
  { emoji: Emojis.Alphanum5, name: 'Alphanum5' },
  { emoji: Emojis.Alphanum6, name: 'Alphanum6' },
  { emoji: Emojis.Alphanum7, name: 'Alphanum7' },
  { emoji: Emojis.Alphanum8, name: 'Alphanum8' },
  { emoji: Emojis.Alphanum9, name: 'Alphanum9' },
];
  