/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../symbols/arrow';

export const EMOJI_LIST = [
  { emoji: Emojis.Arrow1, name: 'Arrow1' },
  { emoji: Emojis.Arrow10, name: 'Arrow10' },
  { emoji: Emojis.Arrow11, name: 'Arrow11' },
  { emoji: Emojis.Arrow12, name: 'Arrow12' },
  { emoji: Emojis.Arrow13, name: 'Arrow13' },
  { emoji: Emojis.Arrow14, name: 'Arrow14' },
  { emoji: Emojis.Arrow15, name: 'Arrow15' },
  { emoji: Emojis.Arrow16, name: 'Arrow16' },
  { emoji: Emojis.Arrow17, name: 'Arrow17' },
  { emoji: Emojis.Arrow18, name: 'Arrow18' },
  { emoji: Emojis.Arrow19, name: 'Arrow19' },
  { emoji: Emojis.Arrow2, name: 'Arrow2' },
  { emoji: Emojis.Arrow20, name: 'Arrow20' },
  { emoji: Emojis.Arrow21, name: 'Arrow21' },
  { emoji: Emojis.Arrow3, name: 'Arrow3' },
  { emoji: Emojis.Arrow4, name: 'Arrow4' },
  { emoji: Emojis.Arrow5, name: 'Arrow5' },
  { emoji: Emojis.Arrow6, name: 'Arrow6' },
  { emoji: Emojis.Arrow7, name: 'Arrow7' },
  { emoji: Emojis.Arrow8, name: 'Arrow8' },
  { emoji: Emojis.Arrow9, name: 'Arrow9' },
];
  