/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../symbols/av-symbol';
     
export const EMOJI_LIST = [
  { emoji: Emojis.AvSymbol1, name: 'AvSymbol1' },
  { emoji: Emojis.AvSymbol10, name: 'AvSymbol10' },
  { emoji: Emojis.AvSymbol11, name: 'AvSymbol11' },
  { emoji: Emojis.AvSymbol12, name: 'AvSymbol12' },
  { emoji: Emojis.AvSymbol13, name: 'AvSymbol13' },
  { emoji: Emojis.AvSymbol14, name: 'AvSymbol14' },
  { emoji: Emojis.AvSymbol15, name: 'AvSymbol15' },
  { emoji: Emojis.AvSymbol16, name: 'AvSymbol16' },
  { emoji: Emojis.AvSymbol17, name: 'AvSymbol17' },
  { emoji: Emojis.AvSymbol18, name: 'AvSymbol18' },
  { emoji: Emojis.AvSymbol19, name: 'AvSymbol19' },
  { emoji: Emojis.AvSymbol2, name: 'AvSymbol2' },
  { emoji: Emojis.AvSymbol20, name: 'AvSymbol20' },
  { emoji: Emojis.AvSymbol21, name: 'AvSymbol21' },
  { emoji: Emojis.AvSymbol22, name: 'AvSymbol22' },
  { emoji: Emojis.AvSymbol23, name: 'AvSymbol23' },
  { emoji: Emojis.AvSymbol24, name: 'AvSymbol24' },
  { emoji: Emojis.AvSymbol3, name: 'AvSymbol3' },
  { emoji: Emojis.AvSymbol4, name: 'AvSymbol4' },
  { emoji: Emojis.AvSymbol5, name: 'AvSymbol5' },
  { emoji: Emojis.AvSymbol6, name: 'AvSymbol6' },
  { emoji: Emojis.AvSymbol7, name: 'AvSymbol7' },
  { emoji: Emojis.AvSymbol8, name: 'AvSymbol8' },
  { emoji: Emojis.AvSymbol9, name: 'AvSymbol9' },
];
  