/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../symbols/currency';

export const EMOJI_LIST = [
  { emoji: Emojis.Currency1, name: 'Currency1' },
  { emoji: Emojis.Currency2, name: 'Currency2' },
];
  