/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../symbols/gender';

export const EMOJI_LIST = [
  { emoji: Emojis.Gender1, name: 'Gender1' },
  { emoji: Emojis.Gender2, name: 'Gender2' },
  { emoji: Emojis.Gender3, name: 'Gender3' },
];
  