/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../symbols/geometric';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Geometric1, name: 'Geometric1' },
  { emoji: Emojis.Geometric10, name: 'Geometric10' },
  { emoji: Emojis.Geometric11, name: 'Geometric11' },
  { emoji: Emojis.Geometric12, name: 'Geometric12' },
  { emoji: Emojis.Geometric13, name: 'Geometric13' },
  { emoji: Emojis.Geometric14, name: 'Geometric14' },
  { emoji: Emojis.Geometric15, name: 'Geometric15' },
  { emoji: Emojis.Geometric16, name: 'Geometric16' },
  { emoji: Emojis.Geometric17, name: 'Geometric17' },
  { emoji: Emojis.Geometric18, name: 'Geometric18' },
  { emoji: Emojis.Geometric19, name: 'Geometric19' },
  { emoji: Emojis.Geometric2, name: 'Geometric2' },
  { emoji: Emojis.Geometric20, name: 'Geometric20' },
  { emoji: Emojis.Geometric21, name: 'Geometric21' },
  { emoji: Emojis.Geometric22, name: 'Geometric22' },
  { emoji: Emojis.Geometric23, name: 'Geometric23' },
  { emoji: Emojis.Geometric24, name: 'Geometric24' },
  { emoji: Emojis.Geometric25, name: 'Geometric25' },
  { emoji: Emojis.Geometric26, name: 'Geometric26' },
  { emoji: Emojis.Geometric27, name: 'Geometric27' },
  { emoji: Emojis.Geometric28, name: 'Geometric28' },
  { emoji: Emojis.Geometric29, name: 'Geometric29' },
  { emoji: Emojis.Geometric3, name: 'Geometric3' },
  { emoji: Emojis.Geometric30, name: 'Geometric30' },
  { emoji: Emojis.Geometric31, name: 'Geometric31' },
  { emoji: Emojis.Geometric32, name: 'Geometric32' },
  { emoji: Emojis.Geometric33, name: 'Geometric33' },
  { emoji: Emojis.Geometric34, name: 'Geometric34' },
  { emoji: Emojis.Geometric4, name: 'Geometric4' },
  { emoji: Emojis.Geometric5, name: 'Geometric5' },
  { emoji: Emojis.Geometric6, name: 'Geometric6' },
  { emoji: Emojis.Geometric7, name: 'Geometric7' },
  { emoji: Emojis.Geometric8, name: 'Geometric8' },
  { emoji: Emojis.Geometric9, name: 'Geometric9' },
];
  