/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../symbols/keycap';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Keycap1, name: 'Keycap1' },
  { emoji: Emojis.Keycap10, name: 'Keycap10' },
  { emoji: Emojis.Keycap11, name: 'Keycap11' },
  { emoji: Emojis.Keycap12, name: 'Keycap12' },
  { emoji: Emojis.Keycap13, name: 'Keycap13' },
  { emoji: Emojis.Keycap2, name: 'Keycap2' },
  { emoji: Emojis.Keycap3, name: 'Keycap3' },
  { emoji: Emojis.Keycap4, name: 'Keycap4' },
  { emoji: Emojis.Keycap5, name: 'Keycap5' },
  { emoji: Emojis.Keycap6, name: 'Keycap6' },
  { emoji: Emojis.Keycap7, name: 'Keycap7' },
  { emoji: Emojis.Keycap8, name: 'Keycap8' },
  { emoji: Emojis.Keycap9, name: 'Keycap9' },
];
  