/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../symbols/math';

export const EMOJI_LIST = [
  { emoji: Emojis.Math1, name: 'Math1' },
  { emoji: Emojis.Math2, name: 'Math2' },
  { emoji: Emojis.Math3, name: 'Math3' },
  { emoji: Emojis.Math4, name: 'Math4' },
  { emoji: Emojis.Math5, name: 'Math5' },
];
  