/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../symbols/other-symbol';
     
export const EMOJI_LIST = [
  { emoji: Emojis.OtherSymbol1, name: 'OtherSymbol1' },
  { emoji: Emojis.OtherSymbol10, name: 'OtherSymbol10' },
  { emoji: Emojis.OtherSymbol11, name: 'OtherSymbol11' },
  { emoji: Emojis.OtherSymbol12, name: 'OtherSymbol12' },
  { emoji: Emojis.OtherSymbol13, name: 'OtherSymbol13' },
  { emoji: Emojis.OtherSymbol14, name: 'OtherSymbol14' },
  { emoji: Emojis.OtherSymbol15, name: 'OtherSymbol15' },
  { emoji: Emojis.OtherSymbol16, name: 'OtherSymbol16' },
  { emoji: Emojis.OtherSymbol17, name: 'OtherSymbol17' },
  { emoji: Emojis.OtherSymbol18, name: 'OtherSymbol18' },
  { emoji: Emojis.OtherSymbol19, name: 'OtherSymbol19' },
  { emoji: Emojis.OtherSymbol2, name: 'OtherSymbol2' },
  { emoji: Emojis.OtherSymbol20, name: 'OtherSymbol20' },
  { emoji: Emojis.OtherSymbol21, name: 'OtherSymbol21' },
  { emoji: Emojis.OtherSymbol3, name: 'OtherSymbol3' },
  { emoji: Emojis.OtherSymbol4, name: 'OtherSymbol4' },
  { emoji: Emojis.OtherSymbol5, name: 'OtherSymbol5' },
  { emoji: Emojis.OtherSymbol6, name: 'OtherSymbol6' },
  { emoji: Emojis.OtherSymbol7, name: 'OtherSymbol7' },
  { emoji: Emojis.OtherSymbol8, name: 'OtherSymbol8' },
  { emoji: Emojis.OtherSymbol9, name: 'OtherSymbol9' },
];
  