/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../symbols/punctuation';

export const EMOJI_LIST = [
  { emoji: Emojis.Punctuation1, name: 'Punctuation1' },
  { emoji: Emojis.Punctuation2, name: 'Punctuation2' },
  { emoji: Emojis.Punctuation3, name: 'Punctuation3' },
  { emoji: Emojis.Punctuation4, name: 'Punctuation4' },
  { emoji: Emojis.Punctuation5, name: 'Punctuation5' },
  { emoji: Emojis.Punctuation6, name: 'Punctuation6' },
  { emoji: Emojis.Punctuation7, name: 'Punctuation7' },
];
  