/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../symbols/religion';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Religion1, name: 'Religion1' },
  { emoji: Emojis.Religion10, name: 'Religion10' },
  { emoji: Emojis.Religion11, name: 'Religion11' },
  { emoji: Emojis.Religion12, name: 'Religion12' },
  { emoji: Emojis.Religion2, name: 'Religion2' },
  { emoji: Emojis.Religion3, name: 'Religion3' },
  { emoji: Emojis.Religion4, name: 'Religion4' },
  { emoji: Emojis.Religion5, name: 'Religion5' },
  { emoji: Emojis.Religion6, name: 'Religion6' },
  { emoji: Emojis.Religion7, name: 'Religion7' },
  { emoji: Emojis.Religion8, name: 'Religion8' },
  { emoji: Emojis.Religion9, name: 'Religion9' },
];
  