/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../symbols/transport-sign';

export const EMOJI_LIST = [
  { emoji: Emojis.TransportSign1, name: 'TransportSign1' },
  { emoji: Emojis.TransportSign10, name: 'TransportSign10' },
  { emoji: Emojis.TransportSign11, name: 'TransportSign11' },
  { emoji: Emojis.TransportSign12, name: 'TransportSign12' },
  { emoji: Emojis.TransportSign13, name: 'TransportSign13' },
  { emoji: Emojis.TransportSign2, name: 'TransportSign2' },
  { emoji: Emojis.TransportSign3, name: 'TransportSign3' },
  { emoji: Emojis.TransportSign4, name: 'TransportSign4' },
  { emoji: Emojis.TransportSign5, name: 'TransportSign5' },
  { emoji: Emojis.TransportSign6, name: 'TransportSign6' },
  { emoji: Emojis.TransportSign7, name: 'TransportSign7' },
  { emoji: Emojis.TransportSign8, name: 'TransportSign8' },
  { emoji: Emojis.TransportSign9, name: 'TransportSign9' },
];
  