/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../symbols/warning';

export const EMOJI_LIST = [
  { emoji: Emojis.Warning1, name: 'Warning1' },
  { emoji: Emojis.Warning10, name: 'Warning10' },
  { emoji: Emojis.Warning11, name: 'Warning11' },
  { emoji: Emojis.Warning12, name: 'Warning12' },
  { emoji: Emojis.Warning13, name: 'Warning13' },
  { emoji: Emojis.Warning2, name: 'Warning2' },
  { emoji: Emojis.Warning3, name: 'Warning3' },
  { emoji: Emojis.Warning4, name: 'Warning4' },
  { emoji: Emojis.Warning5, name: 'Warning5' },
  { emoji: Emojis.Warning6, name: 'Warning6' },
  { emoji: Emojis.Warning7, name: 'Warning7' },
  { emoji: Emojis.Warning8, name: 'Warning8' },
  { emoji: Emojis.Warning9, name: 'Warning9' },
];
  