/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../symbols/zodiac';

export const EMOJI_LIST = [
  { emoji: Emojis.Zodiac1, name: 'Zodiac1' },
  { emoji: Emojis.Zodiac10, name: 'Zodiac10' },
  { emoji: Emojis.Zodiac11, name: 'Zodiac11' },
  { emoji: Emojis.Zodiac12, name: 'Zodiac12' },
  { emoji: Emojis.Zodiac13, name: 'Zodiac13' },
  { emoji: Emojis.Zodiac2, name: 'Zodiac2' },
  { emoji: Emojis.Zodiac3, name: 'Zodiac3' },
  { emoji: Emojis.Zodiac4, name: 'Zodiac4' },
  { emoji: Emojis.Zodiac5, name: 'Zodiac5' },
  { emoji: Emojis.Zodiac6, name: 'Zodiac6' },
  { emoji: Emojis.Zodiac7, name: 'Zodiac7' },
  { emoji: Emojis.Zodiac8, name: 'Zodiac8' },
  { emoji: Emojis.Zodiac9, name: 'Zodiac9' },
];
  