/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../food-drink/dishware';

export const EMOJI_LIST = [
  { emoji: Emojis.Dishware1, name: 'Dishware1' },
  { emoji: Emojis.Dishware2, name: 'Dishware2' },
  { emoji: Emojis.Dishware3, name: 'Dishware3' },
  { emoji: Emojis.Dishware4, name: 'Dishware4' },
  { emoji: Emojis.Dishware5, name: 'Dishware5' },
  { emoji: Emojis.Dishware6, name: 'Dishware6' },
];
  