/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../food-drink/drink';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Drink1, name: 'Drink1' },
  { emoji: Emojis.Drink10, name: 'Drink10' },
  { emoji: Emojis.Drink11, name: 'Drink11' },
  { emoji: Emojis.Drink12, name: 'Drink12' },
  { emoji: Emojis.Drink13, name: 'Drink13' },
  { emoji: Emojis.Drink14, name: 'Drink14' },
  { emoji: Emojis.Drink15, name: 'Drink15' },
  { emoji: Emojis.Drink16, name: 'Drink16' },
  { emoji: Emojis.Drink17, name: 'Drink17' },
  { emoji: Emojis.Drink2, name: 'Drink2' },
  { emoji: Emojis.Drink3, name: 'Drink3' },
  { emoji: Emojis.Drink4, name: 'Drink4' },
  { emoji: Emojis.Drink5, name: 'Drink5' },
  { emoji: Emojis.Drink6, name: 'Drink6' },
  { emoji: Emojis.Drink7, name: 'Drink7' },
  { emoji: Emojis.Drink8, name: 'Drink8' },
  { emoji: Emojis.Drink9, name: 'Drink9' },
];
  