/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../food-drink/food-asian';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FoodAsian1, name: 'FoodAsian1' },
  { emoji: Emojis.FoodAsian10, name: 'FoodAsian10' },
  { emoji: Emojis.FoodAsian11, name: 'FoodAsian11' },
  { emoji: Emojis.FoodAsian12, name: 'FoodAsian12' },
  { emoji: Emojis.FoodAsian13, name: 'FoodAsian13' },
  { emoji: Emojis.FoodAsian14, name: 'FoodAsian14' },
  { emoji: Emojis.FoodAsian15, name: 'FoodAsian15' },
  { emoji: Emojis.FoodAsian16, name: 'FoodAsian16' },
  { emoji: Emojis.FoodAsian17, name: 'FoodAsian17' },
  { emoji: Emojis.FoodAsian2, name: 'FoodAsian2' },
  { emoji: Emojis.FoodAsian3, name: 'FoodAsian3' },
  { emoji: Emojis.FoodAsian4, name: 'FoodAsian4' },
  { emoji: Emojis.FoodAsian5, name: 'FoodAsian5' },
  { emoji: Emojis.FoodAsian6, name: 'FoodAsian6' },
  { emoji: Emojis.FoodAsian7, name: 'FoodAsian7' },
  { emoji: Emojis.FoodAsian8, name: 'FoodAsian8' },
  { emoji: Emojis.FoodAsian9, name: 'FoodAsian9' },
];
  