/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../food-drink/food-fruit';

export const EMOJI_LIST = [
  { emoji: Emojis.FoodFruit1, name: 'FoodFruit1' },
  { emoji: Emojis.FoodFruit10, name: 'FoodFruit10' },
  { emoji: Emojis.FoodFruit11, name: 'FoodFruit11' },
  { emoji: Emojis.FoodFruit12, name: 'FoodFruit12' },
  { emoji: Emojis.FoodFruit13, name: 'FoodFruit13' },
  { emoji: Emojis.FoodFruit14, name: 'FoodFruit14' },
  { emoji: Emojis.FoodFruit15, name: 'FoodFruit15' },
  { emoji: Emojis.FoodFruit16, name: 'FoodFruit16' },
  { emoji: Emojis.FoodFruit17, name: 'FoodFruit17' },
  { emoji: Emojis.FoodFruit18, name: 'FoodFruit18' },
  { emoji: Emojis.FoodFruit19, name: 'FoodFruit19' },
  { emoji: Emojis.FoodFruit2, name: 'FoodFruit2' },
  { emoji: Emojis.FoodFruit3, name: 'FoodFruit3' },
  { emoji: Emojis.FoodFruit4, name: 'FoodFruit4' },
  { emoji: Emojis.FoodFruit5, name: 'FoodFruit5' },
  { emoji: Emojis.FoodFruit6, name: 'FoodFruit6' },
  { emoji: Emojis.FoodFruit7, name: 'FoodFruit7' },
  { emoji: Emojis.FoodFruit8, name: 'FoodFruit8' },
  { emoji: Emojis.FoodFruit9, name: 'FoodFruit9' },
];
  