/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../food-drink/food-marine';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FoodMarine1, name: 'FoodMarine1' },
  { emoji: Emojis.FoodMarine2, name: 'FoodMarine2' },
  { emoji: Emojis.FoodMarine3, name: 'FoodMarine3' },
  { emoji: Emojis.FoodMarine4, name: 'FoodMarine4' },
  { emoji: Emojis.FoodMarine5, name: 'FoodMarine5' },
];
  