/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../food-drink/food-sweet';

export const EMOJI_LIST = [
  { emoji: Emojis.FoodSweet1, name: 'FoodSweet1' },
  { emoji: Emojis.FoodSweet10, name: 'FoodSweet10' },
  { emoji: Emojis.FoodSweet11, name: 'FoodSweet11' },
  { emoji: Emojis.FoodSweet12, name: 'FoodSweet12' },
  { emoji: Emojis.FoodSweet13, name: 'FoodSweet13' },
  { emoji: Emojis.FoodSweet14, name: 'FoodSweet14' },
  { emoji: Emojis.FoodSweet2, name: 'FoodSweet2' },
  { emoji: Emojis.FoodSweet3, name: 'FoodSweet3' },
  { emoji: Emojis.FoodSweet4, name: 'FoodSweet4' },
  { emoji: Emojis.FoodSweet5, name: 'FoodSweet5' },
  { emoji: Emojis.FoodSweet6, name: 'FoodSweet6' },
  { emoji: Emojis.FoodSweet7, name: 'FoodSweet7' },
  { emoji: Emojis.FoodSweet8, name: 'FoodSweet8' },
  { emoji: Emojis.FoodSweet9, name: 'FoodSweet9' },
];
  