/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../food-drink/food-prepared';
     
export const EMOJI_LIST = [
  { emoji: Emojis.FoodPrepared1, name: 'FoodPrepared1' },
  { emoji: Emojis.FoodPrepared10, name: 'FoodPrepared10' },
  { emoji: Emojis.FoodPrepared11, name: 'FoodPrepared11' },
  { emoji: Emojis.FoodPrepared12, name: 'FoodPrepared12' },
  { emoji: Emojis.FoodPrepared13, name: 'FoodPrepared13' },
  { emoji: Emojis.FoodPrepared14, name: 'FoodPrepared14' },
  { emoji: Emojis.FoodPrepared15, name: 'FoodPrepared15' },
  { emoji: Emojis.FoodPrepared16, name: 'FoodPrepared16' },
  { emoji: Emojis.FoodPrepared17, name: 'FoodPrepared17' },
  { emoji: Emojis.FoodPrepared18, name: 'FoodPrepared18' },
  { emoji: Emojis.FoodPrepared19, name: 'FoodPrepared19' },
  { emoji: Emojis.FoodPrepared2, name: 'FoodPrepared2' },
  { emoji: Emojis.FoodPrepared20, name: 'FoodPrepared20' },
  { emoji: Emojis.FoodPrepared21, name: 'FoodPrepared21' },
  { emoji: Emojis.FoodPrepared22, name: 'FoodPrepared22' },
  { emoji: Emojis.FoodPrepared23, name: 'FoodPrepared23' },
  { emoji: Emojis.FoodPrepared24, name: 'FoodPrepared24' },
  { emoji: Emojis.FoodPrepared25, name: 'FoodPrepared25' },
  { emoji: Emojis.FoodPrepared26, name: 'FoodPrepared26' },
  { emoji: Emojis.FoodPrepared27, name: 'FoodPrepared27' },
  { emoji: Emojis.FoodPrepared28, name: 'FoodPrepared28' },
  { emoji: Emojis.FoodPrepared29, name: 'FoodPrepared29' },
  { emoji: Emojis.FoodPrepared3, name: 'FoodPrepared3' },
  { emoji: Emojis.FoodPrepared30, name: 'FoodPrepared30' },
  { emoji: Emojis.FoodPrepared31, name: 'FoodPrepared31' },
  { emoji: Emojis.FoodPrepared32, name: 'FoodPrepared32' },
  { emoji: Emojis.FoodPrepared33, name: 'FoodPrepared33' },
  { emoji: Emojis.FoodPrepared4, name: 'FoodPrepared4' },
  { emoji: Emojis.FoodPrepared5, name: 'FoodPrepared5' },
  { emoji: Emojis.FoodPrepared6, name: 'FoodPrepared6' },
  { emoji: Emojis.FoodPrepared7, name: 'FoodPrepared7' },
  { emoji: Emojis.FoodPrepared8, name: 'FoodPrepared8' },
  { emoji: Emojis.FoodPrepared9, name: 'FoodPrepared9' },
];
  