/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../food-drink/food-vegetable';

export const EMOJI_LIST = [
  { emoji: Emojis.FoodVegetable1, name: 'FoodVegetable1' },
  { emoji: Emojis.FoodVegetable10, name: 'FoodVegetable10' },
  { emoji: Emojis.FoodVegetable11, name: 'FoodVegetable11' },
  { emoji: Emojis.FoodVegetable12, name: 'FoodVegetable12' },
  { emoji: Emojis.FoodVegetable13, name: 'FoodVegetable13' },
  { emoji: Emojis.FoodVegetable14, name: 'FoodVegetable14' },
  { emoji: Emojis.FoodVegetable2, name: 'FoodVegetable2' },
  { emoji: Emojis.FoodVegetable3, name: 'FoodVegetable3' },
  { emoji: Emojis.FoodVegetable4, name: 'FoodVegetable4' },
  { emoji: Emojis.FoodVegetable5, name: 'FoodVegetable5' },
  { emoji: Emojis.FoodVegetable6, name: 'FoodVegetable6' },
  { emoji: Emojis.FoodVegetable7, name: 'FoodVegetable7' },
  { emoji: Emojis.FoodVegetable8, name: 'FoodVegetable8' },
  { emoji: Emojis.FoodVegetable9, name: 'FoodVegetable9' },
];
  