export { default as Lock1 } from './Lock1'
export { default as Lock2 } from './Lock2'
export { default as Lock3 } from './Lock3'
export { default as Lock4 } from './Lock4'
export { default as Lock5 } from './Lock5'
export { default as Lock6 } from './Lock6'