/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/book-paper';
     
export const EMOJI_LIST = [
  { emoji: Emojis.BookPaper1, name: 'BookPaper1' },
  { emoji: Emojis.BookPaper10, name: 'BookPaper10' },
  { emoji: Emojis.BookPaper11, name: 'BookPaper11' },
  { emoji: Emojis.BookPaper12, name: 'BookPaper12' },
  { emoji: Emojis.BookPaper13, name: 'BookPaper13' },
  { emoji: Emojis.BookPaper14, name: 'BookPaper14' },
  { emoji: Emojis.BookPaper15, name: 'BookPaper15' },
  { emoji: Emojis.BookPaper16, name: 'BookPaper16' },
  { emoji: Emojis.BookPaper17, name: 'BookPaper17' },
  { emoji: Emojis.BookPaper2, name: 'BookPaper2' },
  { emoji: Emojis.BookPaper3, name: 'BookPaper3' },
  { emoji: Emojis.BookPaper4, name: 'BookPaper4' },
  { emoji: Emojis.BookPaper5, name: 'BookPaper5' },
  { emoji: Emojis.BookPaper6, name: 'BookPaper6' },
  { emoji: Emojis.BookPaper7, name: 'BookPaper7' },
  { emoji: Emojis.BookPaper8, name: 'BookPaper8' },
  { emoji: Emojis.BookPaper9, name: 'BookPaper9' },
];
  