/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../objects/clothing';

export const EMOJI_LIST = [
  { emoji: Emojis.Clothing1, name: 'Clothing1' },
  { emoji: Emojis.Clothing10, name: 'Clothing10' },
  { emoji: Emojis.Clothing11, name: 'Clothing11' },
  { emoji: Emojis.Clothing12, name: 'Clothing12' },
  { emoji: Emojis.Clothing13, name: 'Clothing13' },
  { emoji: Emojis.Clothing14, name: 'Clothing14' },
  { emoji: Emojis.Clothing15, name: 'Clothing15' },
  { emoji: Emojis.Clothing16, name: 'Clothing16' },
  { emoji: Emojis.Clothing17, name: 'Clothing17' },
  { emoji: Emojis.Clothing18, name: 'Clothing18' },
  { emoji: Emojis.Clothing19, name: 'Clothing19' },
  { emoji: Emojis.Clothing2, name: 'Clothing2' },
  { emoji: Emojis.Clothing20, name: 'Clothing20' },
  { emoji: Emojis.Clothing21, name: 'Clothing21' },
  { emoji: Emojis.Clothing22, name: 'Clothing22' },
  { emoji: Emojis.Clothing23, name: 'Clothing23' },
  { emoji: Emojis.Clothing24, name: 'Clothing24' },
  { emoji: Emojis.Clothing25, name: 'Clothing25' },
  { emoji: Emojis.Clothing26, name: 'Clothing26' },
  { emoji: Emojis.Clothing27, name: 'Clothing27' },
  { emoji: Emojis.Clothing28, name: 'Clothing28' },
  { emoji: Emojis.Clothing29, name: 'Clothing29' },
  { emoji: Emojis.Clothing3, name: 'Clothing3' },
  { emoji: Emojis.Clothing30, name: 'Clothing30' },
  { emoji: Emojis.Clothing31, name: 'Clothing31' },
  { emoji: Emojis.Clothing32, name: 'Clothing32' },
  { emoji: Emojis.Clothing33, name: 'Clothing33' },
  { emoji: Emojis.Clothing34, name: 'Clothing34' },
  { emoji: Emojis.Clothing35, name: 'Clothing35' },
  { emoji: Emojis.Clothing36, name: 'Clothing36' },
  { emoji: Emojis.Clothing37, name: 'Clothing37' },
  { emoji: Emojis.Clothing38, name: 'Clothing38' },
  { emoji: Emojis.Clothing39, name: 'Clothing39' },
  { emoji: Emojis.Clothing4, name: 'Clothing4' },
  { emoji: Emojis.Clothing40, name: 'Clothing40' },
  { emoji: Emojis.Clothing41, name: 'Clothing41' },
  { emoji: Emojis.Clothing42, name: 'Clothing42' },
  { emoji: Emojis.Clothing43, name: 'Clothing43' },
  { emoji: Emojis.Clothing44, name: 'Clothing44' },
  { emoji: Emojis.Clothing5, name: 'Clothing5' },
  { emoji: Emojis.Clothing6, name: 'Clothing6' },
  { emoji: Emojis.Clothing7, name: 'Clothing7' },
  { emoji: Emojis.Clothing8, name: 'Clothing8' },
  { emoji: Emojis.Clothing9, name: 'Clothing9' },
];
  