/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/computer';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Computer1, name: 'Computer1' },
  { emoji: Emojis.Computer10, name: 'Computer10' },
  { emoji: Emojis.Computer11, name: 'Computer11' },
  { emoji: Emojis.Computer12, name: 'Computer12' },
  { emoji: Emojis.Computer13, name: 'Computer13' },
  { emoji: Emojis.Computer2, name: 'Computer2' },
  { emoji: Emojis.Computer3, name: 'Computer3' },
  { emoji: Emojis.Computer4, name: 'Computer4' },
  { emoji: Emojis.Computer5, name: 'Computer5' },
  { emoji: Emojis.Computer6, name: 'Computer6' },
  { emoji: Emojis.Computer7, name: 'Computer7' },
  { emoji: Emojis.Computer8, name: 'Computer8' },
  { emoji: Emojis.Computer9, name: 'Computer9' },
];
  