/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/household';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Household1, name: 'Household1' },
  { emoji: Emojis.Household10, name: 'Household10' },
  { emoji: Emojis.Household11, name: 'Household11' },
  { emoji: Emojis.Household12, name: 'Household12' },
  { emoji: Emojis.Household13, name: 'Household13' },
  { emoji: Emojis.Household14, name: 'Household14' },
  { emoji: Emojis.Household15, name: 'Household15' },
  { emoji: Emojis.Household16, name: 'Household16' },
  { emoji: Emojis.Household17, name: 'Household17' },
  { emoji: Emojis.Household18, name: 'Household18' },
  { emoji: Emojis.Household19, name: 'Household19' },
  { emoji: Emojis.Household2, name: 'Household2' },
  { emoji: Emojis.Household20, name: 'Household20' },
  { emoji: Emojis.Household21, name: 'Household21' },
  { emoji: Emojis.Household22, name: 'Household22' },
  { emoji: Emojis.Household3, name: 'Household3' },
  { emoji: Emojis.Household4, name: 'Household4' },
  { emoji: Emojis.Household5, name: 'Household5' },
  { emoji: Emojis.Household6, name: 'Household6' },
  { emoji: Emojis.Household7, name: 'Household7' },
  { emoji: Emojis.Household8, name: 'Household8' },
  { emoji: Emojis.Household9, name: 'Household9' },
];
  