/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/light-video';
     
export const EMOJI_LIST = [
  { emoji: Emojis.LightVideo1, name: 'LightVideo1' },
  { emoji: Emojis.LightVideo10, name: 'LightVideo10' },
  { emoji: Emojis.LightVideo11, name: 'LightVideo11' },
  { emoji: Emojis.LightVideo12, name: 'LightVideo12' },
  { emoji: Emojis.LightVideo13, name: 'LightVideo13' },
  { emoji: Emojis.LightVideo14, name: 'LightVideo14' },
  { emoji: Emojis.LightVideo15, name: 'LightVideo15' },
  { emoji: Emojis.LightVideo16, name: 'LightVideo16' },
  { emoji: Emojis.LightVideo2, name: 'LightVideo2' },
  { emoji: Emojis.LightVideo3, name: 'LightVideo3' },
  { emoji: Emojis.LightVideo4, name: 'LightVideo4' },
  { emoji: Emojis.LightVideo5, name: 'LightVideo5' },
  { emoji: Emojis.LightVideo6, name: 'LightVideo6' },
  { emoji: Emojis.LightVideo7, name: 'LightVideo7' },
  { emoji: Emojis.LightVideo8, name: 'LightVideo8' },
  { emoji: Emojis.LightVideo9, name: 'LightVideo9' },
];
  