/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/lock';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Lock1, name: 'Lock1' },
  { emoji: Emojis.Lock2, name: 'Lock2' },
  { emoji: Emojis.Lock3, name: 'Lock3' },
  { emoji: Emojis.Lock4, name: 'Lock4' },
  { emoji: Emojis.Lock5, name: 'Lock5' },
  { emoji: Emojis.Lock6, name: 'Lock6' },
];
  