/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/mail';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Mail1, name: 'Mail1' },
  { emoji: Emojis.Mail10, name: 'Mail10' },
  { emoji: Emojis.Mail11, name: 'Mail11' },
  { emoji: Emojis.Mail12, name: 'Mail12' },
  { emoji: Emojis.Mail13, name: 'Mail13' },
  { emoji: Emojis.Mail2, name: 'Mail2' },
  { emoji: Emojis.Mail3, name: 'Mail3' },
  { emoji: Emojis.Mail4, name: 'Mail4' },
  { emoji: Emojis.Mail5, name: 'Mail5' },
  { emoji: Emojis.Mail6, name: 'Mail6' },
  { emoji: Emojis.Mail7, name: 'Mail7' },
  { emoji: Emojis.Mail8, name: 'Mail8' },
  { emoji: Emojis.Mail9, name: 'Mail9' },
];
  