/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../objects/medical';

export const EMOJI_LIST = [
  { emoji: Emojis.Medical1, name: 'Medical1' },
  { emoji: Emojis.Medical2, name: 'Medical2' },
  { emoji: Emojis.Medical3, name: 'Medical3' },
  { emoji: Emojis.Medical4, name: 'Medical4' },
  { emoji: Emojis.Medical5, name: 'Medical5' },
];
  