/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/money';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Money1, name: 'Money1' },
  { emoji: Emojis.Money2, name: 'Money2' },
  { emoji: Emojis.Money3, name: 'Money3' },
  { emoji: Emojis.Money4, name: 'Money4' },
  { emoji: Emojis.Money5, name: 'Money5' },
  { emoji: Emojis.Money6, name: 'Money6' },
  { emoji: Emojis.Money7, name: 'Money7' },
  { emoji: Emojis.Money8, name: 'Money8' },
  { emoji: Emojis.Money9, name: 'Money9' },
];
  