/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../objects/music';

export const EMOJI_LIST = [
  { emoji: Emojis.Music1, name: 'Music1' },
  { emoji: Emojis.Music2, name: 'Music2' },
  { emoji: Emojis.Music3, name: 'Music3' },
  { emoji: Emojis.Music4, name: 'Music4' },
  { emoji: Emojis.Music5, name: 'Music5' },
  { emoji: Emojis.Music6, name: 'Music6' },
  { emoji: Emojis.Music7, name: 'Music7' },
  { emoji: Emojis.Music8, name: 'Music8' },
  { emoji: Emojis.Music9, name: 'Music9' },
];
  