/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/musical-instrument';
     
export const EMOJI_LIST = [
  { emoji: Emojis.MusicalInstrument1, name: 'MusicalInstrument1' },
  { emoji: Emojis.MusicalInstrument2, name: 'MusicalInstrument2' },
  { emoji: Emojis.MusicalInstrument3, name: 'MusicalInstrument3' },
  { emoji: Emojis.MusicalInstrument4, name: 'MusicalInstrument4' },
  { emoji: Emojis.MusicalInstrument5, name: 'MusicalInstrument5' },
  { emoji: Emojis.MusicalInstrument6, name: 'MusicalInstrument6' },
  { emoji: Emojis.MusicalInstrument7, name: 'MusicalInstrument7' },
  { emoji: Emojis.MusicalInstrument8, name: 'MusicalInstrument8' },
];
  