/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../objects/office';

export const EMOJI_LIST = [
  { emoji: Emojis.Office1, name: 'Office1' },
  { emoji: Emojis.Office10, name: 'Office10' },
  { emoji: Emojis.Office11, name: 'Office11' },
  { emoji: Emojis.Office12, name: 'Office12' },
  { emoji: Emojis.Office13, name: 'Office13' },
  { emoji: Emojis.Office14, name: 'Office14' },
  { emoji: Emojis.Office15, name: 'Office15' },
  { emoji: Emojis.Office16, name: 'Office16' },
  { emoji: Emojis.Office17, name: 'Office17' },
  { emoji: Emojis.Office18, name: 'Office18' },
  { emoji: Emojis.Office19, name: 'Office19' },
  { emoji: Emojis.Office2, name: 'Office2' },
  { emoji: Emojis.Office20, name: 'Office20' },
  { emoji: Emojis.Office21, name: 'Office21' },
  { emoji: Emojis.Office22, name: 'Office22' },
  { emoji: Emojis.Office23, name: 'Office23' },
  { emoji: Emojis.Office3, name: 'Office3' },
  { emoji: Emojis.Office4, name: 'Office4' },
  { emoji: Emojis.Office5, name: 'Office5' },
  { emoji: Emojis.Office6, name: 'Office6' },
  { emoji: Emojis.Office7, name: 'Office7' },
  { emoji: Emojis.Office8, name: 'Office8' },
  { emoji: Emojis.Office9, name: 'Office9' },
];
  