/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/other-object';
     
export const EMOJI_LIST = [
  { emoji: Emojis.OtherObject1, name: 'OtherObject1' },
  { emoji: Emojis.OtherObject2, name: 'OtherObject2' },
  { emoji: Emojis.OtherObject3, name: 'OtherObject3' },
  { emoji: Emojis.OtherObject4, name: 'OtherObject4' },
  { emoji: Emojis.OtherObject5, name: 'OtherObject5' },
  { emoji: Emojis.OtherObject6, name: 'OtherObject6' },
];
  