/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/phone';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Phone1, name: 'Phone1' },
  { emoji: Emojis.Phone2, name: 'Phone2' },
  { emoji: Emojis.Phone3, name: 'Phone3' },
  { emoji: Emojis.Phone4, name: 'Phone4' },
  { emoji: Emojis.Phone5, name: 'Phone5' },
  { emoji: Emojis.Phone6, name: 'Phone6' },
];
  