/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/science';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Science1, name: 'Science1' },
  { emoji: Emojis.Science2, name: 'Science2' },
  { emoji: Emojis.Science3, name: 'Science3' },
  { emoji: Emojis.Science4, name: 'Science4' },
  { emoji: Emojis.Science5, name: 'Science5' },
  { emoji: Emojis.Science6, name: 'Science6' },
  { emoji: Emojis.Science7, name: 'Science7' },
];
  