/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../objects/sound';

export const EMOJI_LIST = [
  { emoji: Emojis.Sound1, name: 'Sound1' },
  { emoji: Emojis.Sound2, name: 'Sound2' },
  { emoji: Emojis.Sound3, name: 'Sound3' },
  { emoji: Emojis.Sound4, name: 'Sound4' },
  { emoji: Emojis.Sound5, name: 'Sound5' },
  { emoji: Emojis.Sound6, name: 'Sound6' },
  { emoji: Emojis.Sound7, name: 'Sound7' },
  { emoji: Emojis.Sound8, name: 'Sound8' },
  { emoji: Emojis.Sound9, name: 'Sound9' },
];
  