/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/tool';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Tool1, name: 'Tool1' },
  { emoji: Emojis.Tool10, name: 'Tool10' },
  { emoji: Emojis.Tool11, name: 'Tool11' },
  { emoji: Emojis.Tool12, name: 'Tool12' },
  { emoji: Emojis.Tool13, name: 'Tool13' },
  { emoji: Emojis.Tool14, name: 'Tool14' },
  { emoji: Emojis.Tool15, name: 'Tool15' },
  { emoji: Emojis.Tool16, name: 'Tool16' },
  { emoji: Emojis.Tool17, name: 'Tool17' },
  { emoji: Emojis.Tool18, name: 'Tool18' },
  { emoji: Emojis.Tool19, name: 'Tool19' },
  { emoji: Emojis.Tool2, name: 'Tool2' },
  { emoji: Emojis.Tool20, name: 'Tool20' },
  { emoji: Emojis.Tool21, name: 'Tool21' },
  { emoji: Emojis.Tool22, name: 'Tool22' },
  { emoji: Emojis.Tool23, name: 'Tool23' },
  { emoji: Emojis.Tool24, name: 'Tool24' },
  { emoji: Emojis.Tool3, name: 'Tool3' },
  { emoji: Emojis.Tool4, name: 'Tool4' },
  { emoji: Emojis.Tool5, name: 'Tool5' },
  { emoji: Emojis.Tool6, name: 'Tool6' },
  { emoji: Emojis.Tool7, name: 'Tool7' },
  { emoji: Emojis.Tool8, name: 'Tool8' },
  { emoji: Emojis.Tool9, name: 'Tool9' },
];
  