/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../objects/writing';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Writing1, name: 'Writing1' },
  { emoji: Emojis.Writing2, name: 'Writing2' },
  { emoji: Emojis.Writing3, name: 'Writing3' },
  { emoji: Emojis.Writing4, name: 'Writing4' },
  { emoji: Emojis.Writing5, name: 'Writing5' },
  { emoji: Emojis.Writing6, name: 'Writing6' },
  { emoji: Emojis.Writing7, name: 'Writing7' },
];
  