/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../activities/arts-crafts';
     
export const EMOJI_LIST = [
  { emoji: Emojis.ArtsCrafts1, name: 'ArtsCrafts1' },
  { emoji: Emojis.ArtsCrafts2, name: 'ArtsCrafts2' },
  { emoji: Emojis.ArtsCrafts3, name: 'ArtsCrafts3' },
  { emoji: Emojis.ArtsCrafts4, name: 'ArtsCrafts4' },
  { emoji: Emojis.ArtsCrafts5, name: 'ArtsCrafts5' },
  { emoji: Emojis.ArtsCrafts6, name: 'ArtsCrafts6' },
];
  