/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../activities/award-medal';

export const EMOJI_LIST = [
  { emoji: Emojis.AwardMedal1, name: 'AwardMedal1' },
  { emoji: Emojis.AwardMedal2, name: 'AwardMedal2' },
  { emoji: Emojis.AwardMedal3, name: 'AwardMedal3' },
  { emoji: Emojis.AwardMedal4, name: 'AwardMedal4' },
  { emoji: Emojis.AwardMedal5, name: 'AwardMedal5' },
  { emoji: Emojis.AwardMedal6, name: 'AwardMedal6' },
];
  