/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../activities/event';

export const EMOJI_LIST = [
  { emoji: Emojis.Event1, name: 'Event1' },
  { emoji: Emojis.Event10, name: 'Event10' },
  { emoji: Emojis.Event11, name: 'Event11' },
  { emoji: Emojis.Event12, name: 'Event12' },
  { emoji: Emojis.Event13, name: 'Event13' },
  { emoji: Emojis.Event14, name: 'Event14' },
  { emoji: Emojis.Event15, name: 'Event15' },
  { emoji: Emojis.Event16, name: 'Event16' },
  { emoji: Emojis.Event17, name: 'Event17' },
  { emoji: Emojis.Event18, name: 'Event18' },
  { emoji: Emojis.Event19, name: 'Event19' },
  { emoji: Emojis.Event2, name: 'Event2' },
  { emoji: Emojis.Event20, name: 'Event20' },
  { emoji: Emojis.Event21, name: 'Event21' },
  { emoji: Emojis.Event3, name: 'Event3' },
  { emoji: Emojis.Event4, name: 'Event4' },
  { emoji: Emojis.Event5, name: 'Event5' },
  { emoji: Emojis.Event6, name: 'Event6' },
  { emoji: Emojis.Event7, name: 'Event7' },
  { emoji: Emojis.Event8, name: 'Event8' },
  { emoji: Emojis.Event9, name: 'Event9' },
];
  