/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../activities/game';

export const EMOJI_LIST = [
  { emoji: Emojis.Game1, name: 'Game1' },
  { emoji: Emojis.Game10, name: 'Game10' },
  { emoji: Emojis.Game11, name: 'Game11' },
  { emoji: Emojis.Game12, name: 'Game12' },
  { emoji: Emojis.Game13, name: 'Game13' },
  { emoji: Emojis.Game14, name: 'Game14' },
  { emoji: Emojis.Game15, name: 'Game15' },
  { emoji: Emojis.Game16, name: 'Game16' },
  { emoji: Emojis.Game17, name: 'Game17' },
  { emoji: Emojis.Game18, name: 'Game18' },
  { emoji: Emojis.Game19, name: 'Game19' },
  { emoji: Emojis.Game2, name: 'Game2' },
  { emoji: Emojis.Game20, name: 'Game20' },
  { emoji: Emojis.Game21, name: 'Game21' },
  { emoji: Emojis.Game22, name: 'Game22' },
  { emoji: Emojis.Game23, name: 'Game23' },
  { emoji: Emojis.Game3, name: 'Game3' },
  { emoji: Emojis.Game4, name: 'Game4' },
  { emoji: Emojis.Game5, name: 'Game5' },
  { emoji: Emojis.Game6, name: 'Game6' },
  { emoji: Emojis.Game7, name: 'Game7' },
  { emoji: Emojis.Game8, name: 'Game8' },
  { emoji: Emojis.Game9, name: 'Game9' },
];
  