/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../activities/sport';

export const EMOJI_LIST = [
  { emoji: Emojis.Sport1, name: 'Sport1' },
  { emoji: Emojis.Sport10, name: 'Sport10' },
  { emoji: Emojis.Sport11, name: 'Sport11' },
  { emoji: Emojis.Sport12, name: 'Sport12' },
  { emoji: Emojis.Sport13, name: 'Sport13' },
  { emoji: Emojis.Sport14, name: 'Sport14' },
  { emoji: Emojis.Sport15, name: 'Sport15' },
  { emoji: Emojis.Sport16, name: 'Sport16' },
  { emoji: Emojis.Sport17, name: 'Sport17' },
  { emoji: Emojis.Sport18, name: 'Sport18' },
  { emoji: Emojis.Sport19, name: 'Sport19' },
  { emoji: Emojis.Sport2, name: 'Sport2' },
  { emoji: Emojis.Sport20, name: 'Sport20' },
  { emoji: Emojis.Sport21, name: 'Sport21' },
  { emoji: Emojis.Sport22, name: 'Sport22' },
  { emoji: Emojis.Sport23, name: 'Sport23' },
  { emoji: Emojis.Sport24, name: 'Sport24' },
  { emoji: Emojis.Sport25, name: 'Sport25' },
  { emoji: Emojis.Sport26, name: 'Sport26' },
  { emoji: Emojis.Sport27, name: 'Sport27' },
  { emoji: Emojis.Sport3, name: 'Sport3' },
  { emoji: Emojis.Sport4, name: 'Sport4' },
  { emoji: Emojis.Sport5, name: 'Sport5' },
  { emoji: Emojis.Sport6, name: 'Sport6' },
  { emoji: Emojis.Sport7, name: 'Sport7' },
  { emoji: Emojis.Sport8, name: 'Sport8' },
  { emoji: Emojis.Sport9, name: 'Sport9' },
];
  