/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../travel-places/hotel';

export const EMOJI_LIST = [
  { emoji: Emojis.Hotel1, name: 'Hotel1' },
  { emoji: Emojis.Hotel2, name: 'Hotel2' },
];
  