/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../travel-places/place-religious';

export const EMOJI_LIST = [
  { emoji: Emojis.PlaceReligious1, name: 'PlaceReligious1' },
  { emoji: Emojis.PlaceReligious2, name: 'PlaceReligious2' },
  { emoji: Emojis.PlaceReligious3, name: 'PlaceReligious3' },
  { emoji: Emojis.PlaceReligious4, name: 'PlaceReligious4' },
  { emoji: Emojis.PlaceReligious5, name: 'PlaceReligious5' },
  { emoji: Emojis.PlaceReligious6, name: 'PlaceReligious6' },
];
  