/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../travel-places/place-map';
     
export const EMOJI_LIST = [
  { emoji: Emojis.PlaceMap1, name: 'PlaceMap1' },
  { emoji: Emojis.PlaceMap2, name: 'PlaceMap2' },
  { emoji: Emojis.PlaceMap3, name: 'PlaceMap3' },
  { emoji: Emojis.PlaceMap4, name: 'PlaceMap4' },
  { emoji: Emojis.PlaceMap5, name: 'PlaceMap5' },
  { emoji: Emojis.PlaceMap6, name: 'PlaceMap6' },
  { emoji: Emojis.PlaceMap7, name: 'PlaceMap7' },
];
  