/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../travel-places/place-building';
     
export const EMOJI_LIST = [
  { emoji: Emojis.PlaceBuilding1, name: 'PlaceBuilding1' },
  { emoji: Emojis.PlaceBuilding10, name: 'PlaceBuilding10' },
  { emoji: Emojis.PlaceBuilding11, name: 'PlaceBuilding11' },
  { emoji: Emojis.PlaceBuilding12, name: 'PlaceBuilding12' },
  { emoji: Emojis.PlaceBuilding13, name: 'PlaceBuilding13' },
  { emoji: Emojis.PlaceBuilding14, name: 'PlaceBuilding14' },
  { emoji: Emojis.PlaceBuilding15, name: 'PlaceBuilding15' },
  { emoji: Emojis.PlaceBuilding16, name: 'PlaceBuilding16' },
  { emoji: Emojis.PlaceBuilding17, name: 'PlaceBuilding17' },
  { emoji: Emojis.PlaceBuilding18, name: 'PlaceBuilding18' },
  { emoji: Emojis.PlaceBuilding19, name: 'PlaceBuilding19' },
  { emoji: Emojis.PlaceBuilding2, name: 'PlaceBuilding2' },
  { emoji: Emojis.PlaceBuilding20, name: 'PlaceBuilding20' },
  { emoji: Emojis.PlaceBuilding21, name: 'PlaceBuilding21' },
  { emoji: Emojis.PlaceBuilding22, name: 'PlaceBuilding22' },
  { emoji: Emojis.PlaceBuilding23, name: 'PlaceBuilding23' },
  { emoji: Emojis.PlaceBuilding24, name: 'PlaceBuilding24' },
  { emoji: Emojis.PlaceBuilding3, name: 'PlaceBuilding3' },
  { emoji: Emojis.PlaceBuilding4, name: 'PlaceBuilding4' },
  { emoji: Emojis.PlaceBuilding5, name: 'PlaceBuilding5' },
  { emoji: Emojis.PlaceBuilding6, name: 'PlaceBuilding6' },
  { emoji: Emojis.PlaceBuilding7, name: 'PlaceBuilding7' },
  { emoji: Emojis.PlaceBuilding8, name: 'PlaceBuilding8' },
  { emoji: Emojis.PlaceBuilding9, name: 'PlaceBuilding9' },
];
  