/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../travel-places/place-other';
     
export const EMOJI_LIST = [
  { emoji: Emojis.PlaceOther1, name: 'PlaceOther1' },
  { emoji: Emojis.PlaceOther10, name: 'PlaceOther10' },
  { emoji: Emojis.PlaceOther11, name: 'PlaceOther11' },
  { emoji: Emojis.PlaceOther12, name: 'PlaceOther12' },
  { emoji: Emojis.PlaceOther13, name: 'PlaceOther13' },
  { emoji: Emojis.PlaceOther14, name: 'PlaceOther14' },
  { emoji: Emojis.PlaceOther15, name: 'PlaceOther15' },
  { emoji: Emojis.PlaceOther16, name: 'PlaceOther16' },
  { emoji: Emojis.PlaceOther2, name: 'PlaceOther2' },
  { emoji: Emojis.PlaceOther3, name: 'PlaceOther3' },
  { emoji: Emojis.PlaceOther4, name: 'PlaceOther4' },
  { emoji: Emojis.PlaceOther5, name: 'PlaceOther5' },
  { emoji: Emojis.PlaceOther6, name: 'PlaceOther6' },
  { emoji: Emojis.PlaceOther7, name: 'PlaceOther7' },
  { emoji: Emojis.PlaceOther8, name: 'PlaceOther8' },
  { emoji: Emojis.PlaceOther9, name: 'PlaceOther9' },
];
  