/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../travel-places/place-geographic';

export const EMOJI_LIST = [
  { emoji: Emojis.PlaceGeographic1, name: 'PlaceGeographic1' },
  { emoji: Emojis.PlaceGeographic2, name: 'PlaceGeographic2' },
  { emoji: Emojis.PlaceGeographic3, name: 'PlaceGeographic3' },
  { emoji: Emojis.PlaceGeographic4, name: 'PlaceGeographic4' },
  { emoji: Emojis.PlaceGeographic5, name: 'PlaceGeographic5' },
  { emoji: Emojis.PlaceGeographic6, name: 'PlaceGeographic6' },
  { emoji: Emojis.PlaceGeographic7, name: 'PlaceGeographic7' },
  { emoji: Emojis.PlaceGeographic8, name: 'PlaceGeographic8' },
  { emoji: Emojis.PlaceGeographic9, name: 'PlaceGeographic9' },
];
  