/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../travel-places/time';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Time1, name: 'Time1' },
  { emoji: Emojis.Time10, name: 'Time10' },
  { emoji: Emojis.Time11, name: 'Time11' },
  { emoji: Emojis.Time12, name: 'Time12' },
  { emoji: Emojis.Time13, name: 'Time13' },
  { emoji: Emojis.Time14, name: 'Time14' },
  { emoji: Emojis.Time15, name: 'Time15' },
  { emoji: Emojis.Time16, name: 'Time16' },
  { emoji: Emojis.Time17, name: 'Time17' },
  { emoji: Emojis.Time18, name: 'Time18' },
  { emoji: Emojis.Time19, name: 'Time19' },
  { emoji: Emojis.Time2, name: 'Time2' },
  { emoji: Emojis.Time20, name: 'Time20' },
  { emoji: Emojis.Time21, name: 'Time21' },
  { emoji: Emojis.Time22, name: 'Time22' },
  { emoji: Emojis.Time23, name: 'Time23' },
  { emoji: Emojis.Time24, name: 'Time24' },
  { emoji: Emojis.Time25, name: 'Time25' },
  { emoji: Emojis.Time26, name: 'Time26' },
  { emoji: Emojis.Time27, name: 'Time27' },
  { emoji: Emojis.Time28, name: 'Time28' },
  { emoji: Emojis.Time29, name: 'Time29' },
  { emoji: Emojis.Time3, name: 'Time3' },
  { emoji: Emojis.Time30, name: 'Time30' },
  { emoji: Emojis.Time31, name: 'Time31' },
  { emoji: Emojis.Time4, name: 'Time4' },
  { emoji: Emojis.Time5, name: 'Time5' },
  { emoji: Emojis.Time6, name: 'Time6' },
  { emoji: Emojis.Time7, name: 'Time7' },
  { emoji: Emojis.Time8, name: 'Time8' },
  { emoji: Emojis.Time9, name: 'Time9' },
];
  