/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../travel-places/transport-water';

export const EMOJI_LIST = [
  { emoji: Emojis.TransportWater1, name: 'TransportWater1' },
  { emoji: Emojis.TransportWater2, name: 'TransportWater2' },
  { emoji: Emojis.TransportWater3, name: 'TransportWater3' },
  { emoji: Emojis.TransportWater4, name: 'TransportWater4' },
  { emoji: Emojis.TransportWater5, name: 'TransportWater5' },
  { emoji: Emojis.TransportWater6, name: 'TransportWater6' },
  { emoji: Emojis.TransportWater7, name: 'TransportWater7' },
  { emoji: Emojis.TransportWater8, name: 'TransportWater8' },
];
  