/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../travel-places/transport-air';

export const EMOJI_LIST = [
  { emoji: Emojis.TransportAir1, name: 'TransportAir1' },
  { emoji: Emojis.TransportAir10, name: 'TransportAir10' },
  { emoji: Emojis.TransportAir11, name: 'TransportAir11' },
  { emoji: Emojis.TransportAir12, name: 'TransportAir12' },
  { emoji: Emojis.TransportAir13, name: 'TransportAir13' },
  { emoji: Emojis.TransportAir2, name: 'TransportAir2' },
  { emoji: Emojis.TransportAir3, name: 'TransportAir3' },
  { emoji: Emojis.TransportAir4, name: 'TransportAir4' },
  { emoji: Emojis.TransportAir5, name: 'TransportAir5' },
  { emoji: Emojis.TransportAir6, name: 'TransportAir6' },
  { emoji: Emojis.TransportAir7, name: 'TransportAir7' },
  { emoji: Emojis.TransportAir8, name: 'TransportAir8' },
  { emoji: Emojis.TransportAir9, name: 'TransportAir9' },
];
  