/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../animals-nature/animal-bug';
     
export const EMOJI_LIST = [
  { emoji: Emojis.AnimalBug1, name: 'AnimalBug1' },
  { emoji: Emojis.AnimalBug10, name: 'AnimalBug10' },
  { emoji: Emojis.AnimalBug11, name: 'AnimalBug11' },
  { emoji: Emojis.AnimalBug12, name: 'AnimalBug12' },
  { emoji: Emojis.AnimalBug13, name: 'AnimalBug13' },
  { emoji: Emojis.AnimalBug14, name: 'AnimalBug14' },
  { emoji: Emojis.AnimalBug2, name: 'AnimalBug2' },
  { emoji: Emojis.AnimalBug3, name: 'AnimalBug3' },
  { emoji: Emojis.AnimalBug4, name: 'AnimalBug4' },
  { emoji: Emojis.AnimalBug5, name: 'AnimalBug5' },
  { emoji: Emojis.AnimalBug6, name: 'AnimalBug6' },
  { emoji: Emojis.AnimalBug7, name: 'AnimalBug7' },
  { emoji: Emojis.AnimalBug8, name: 'AnimalBug8' },
  { emoji: Emojis.AnimalBug9, name: 'AnimalBug9' },
];
  