/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../animals-nature/animal-bird';
     
export const EMOJI_LIST = [
  { emoji: Emojis.AnimalBird1, name: 'AnimalBird1' },
  { emoji: Emojis.AnimalBird10, name: 'AnimalBird10' },
  { emoji: Emojis.AnimalBird11, name: 'AnimalBird11' },
  { emoji: Emojis.AnimalBird12, name: 'AnimalBird12' },
  { emoji: Emojis.AnimalBird13, name: 'AnimalBird13' },
  { emoji: Emojis.AnimalBird14, name: 'AnimalBird14' },
  { emoji: Emojis.AnimalBird15, name: 'AnimalBird15' },
  { emoji: Emojis.AnimalBird16, name: 'AnimalBird16' },
  { emoji: Emojis.AnimalBird17, name: 'AnimalBird17' },
  { emoji: Emojis.AnimalBird2, name: 'AnimalBird2' },
  { emoji: Emojis.AnimalBird3, name: 'AnimalBird3' },
  { emoji: Emojis.AnimalBird4, name: 'AnimalBird4' },
  { emoji: Emojis.AnimalBird5, name: 'AnimalBird5' },
  { emoji: Emojis.AnimalBird6, name: 'AnimalBird6' },
  { emoji: Emojis.AnimalBird7, name: 'AnimalBird7' },
  { emoji: Emojis.AnimalBird8, name: 'AnimalBird8' },
  { emoji: Emojis.AnimalBird9, name: 'AnimalBird9' },
];
  