/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../animals-nature/animal-reptile';
     
export const EMOJI_LIST = [
  { emoji: Emojis.AnimalReptile1, name: 'AnimalReptile1' },
  { emoji: Emojis.AnimalReptile2, name: 'AnimalReptile2' },
  { emoji: Emojis.AnimalReptile3, name: 'AnimalReptile3' },
  { emoji: Emojis.AnimalReptile4, name: 'AnimalReptile4' },
  { emoji: Emojis.AnimalReptile5, name: 'AnimalReptile5' },
  { emoji: Emojis.AnimalReptile6, name: 'AnimalReptile6' },
  { emoji: Emojis.AnimalReptile7, name: 'AnimalReptile7' },
  { emoji: Emojis.AnimalReptile8, name: 'AnimalReptile8' },
];
  