/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../animals-nature/animal-marine';

export const EMOJI_LIST = [
  { emoji: Emojis.AnimalMarine1, name: 'AnimalMarine1' },
  { emoji: Emojis.AnimalMarine2, name: 'AnimalMarine2' },
  { emoji: Emojis.AnimalMarine3, name: 'AnimalMarine3' },
  { emoji: Emojis.AnimalMarine4, name: 'AnimalMarine4' },
  { emoji: Emojis.AnimalMarine5, name: 'AnimalMarine5' },
  { emoji: Emojis.AnimalMarine6, name: 'AnimalMarine6' },
  { emoji: Emojis.AnimalMarine7, name: 'AnimalMarine7' },
  { emoji: Emojis.AnimalMarine8, name: 'AnimalMarine8' },
  { emoji: Emojis.AnimalMarine9, name: 'AnimalMarine9' },
];
  