/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../animals-nature/animal-amphibian';
     
export const EMOJI_LIST = [
  { emoji: Emojis.AnimalAmphibian1, name: 'AnimalAmphibian1' },
];
  