/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../animals-nature/plant-flower';
     
export const EMOJI_LIST = [
  { emoji: Emojis.PlantFlower1, name: 'PlantFlower1' },
  { emoji: Emojis.PlantFlower10, name: 'PlantFlower10' },
  { emoji: Emojis.PlantFlower2, name: 'PlantFlower2' },
  { emoji: Emojis.PlantFlower3, name: 'PlantFlower3' },
  { emoji: Emojis.PlantFlower4, name: 'PlantFlower4' },
  { emoji: Emojis.PlantFlower5, name: 'PlantFlower5' },
  { emoji: Emojis.PlantFlower6, name: 'PlantFlower6' },
  { emoji: Emojis.PlantFlower7, name: 'PlantFlower7' },
  { emoji: Emojis.PlantFlower8, name: 'PlantFlower8' },
  { emoji: Emojis.PlantFlower9, name: 'PlantFlower9' },
];
  