/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../animals-nature/plant-other';
     
export const EMOJI_LIST = [
  { emoji: Emojis.PlantOther1, name: 'PlantOther1' },
  { emoji: Emojis.PlantOther10, name: 'PlantOther10' },
  { emoji: Emojis.PlantOther11, name: 'PlantOther11' },
  { emoji: Emojis.PlantOther12, name: 'PlantOther12' },
  { emoji: Emojis.PlantOther13, name: 'PlantOther13' },
  { emoji: Emojis.PlantOther2, name: 'PlantOther2' },
  { emoji: Emojis.PlantOther3, name: 'PlantOther3' },
  { emoji: Emojis.PlantOther4, name: 'PlantOther4' },
  { emoji: Emojis.PlantOther5, name: 'PlantOther5' },
  { emoji: Emojis.PlantOther6, name: 'PlantOther6' },
  { emoji: Emojis.PlantOther7, name: 'PlantOther7' },
  { emoji: Emojis.PlantOther8, name: 'PlantOther8' },
  { emoji: Emojis.PlantOther9, name: 'PlantOther9' },
];
  