/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/animals-nature';
     
export const EMOJI_LIST = [
  { emoji: Emojis.AnimalsNature1, name: 'AnimalsNature1' },
  { emoji: Emojis.AnimalsNature10, name: 'AnimalsNature10' },
  { emoji: Emojis.AnimalsNature11, name: 'AnimalsNature11' },
  { emoji: Emojis.AnimalsNature2, name: 'AnimalsNature2' },
  { emoji: Emojis.AnimalsNature3, name: 'AnimalsNature3' },
  { emoji: Emojis.AnimalsNature4, name: 'AnimalsNature4' },
  { emoji: Emojis.AnimalsNature5, name: 'AnimalsNature5' },
  { emoji: Emojis.AnimalsNature6, name: 'AnimalsNature6' },
  { emoji: Emojis.AnimalsNature7, name: 'AnimalsNature7' },
  { emoji: Emojis.AnimalsNature8, name: 'AnimalsNature8' },
  { emoji: Emojis.AnimalsNature9, name: 'AnimalsNature9' },
];
  