/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/brand';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Brand1, name: 'Brand1' },
  { emoji: Emojis.Brand10, name: 'Brand10' },
  { emoji: Emojis.Brand11, name: 'Brand11' },
  { emoji: Emojis.Brand2, name: 'Brand2' },
  { emoji: Emojis.Brand3, name: 'Brand3' },
  { emoji: Emojis.Brand4, name: 'Brand4' },
  { emoji: Emojis.Brand5, name: 'Brand5' },
  { emoji: Emojis.Brand6, name: 'Brand6' },
  { emoji: Emojis.Brand7, name: 'Brand7' },
  { emoji: Emojis.Brand8, name: 'Brand8' },
  { emoji: Emojis.Brand9, name: 'Brand9' },
];
  