/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/climate-environment';
     
export const EMOJI_LIST = [
  { emoji: Emojis.ClimateEnvironment1, name: 'ClimateEnvironment1' },
  { emoji: Emojis.ClimateEnvironment10, name: 'ClimateEnvironment10' },
  { emoji: Emojis.ClimateEnvironment11, name: 'ClimateEnvironment11' },
  { emoji: Emojis.ClimateEnvironment12, name: 'ClimateEnvironment12' },
  { emoji: Emojis.ClimateEnvironment13, name: 'ClimateEnvironment13' },
  { emoji: Emojis.ClimateEnvironment14, name: 'ClimateEnvironment14' },
  { emoji: Emojis.ClimateEnvironment15, name: 'ClimateEnvironment15' },
  { emoji: Emojis.ClimateEnvironment16, name: 'ClimateEnvironment16' },
  { emoji: Emojis.ClimateEnvironment17, name: 'ClimateEnvironment17' },
  { emoji: Emojis.ClimateEnvironment18, name: 'ClimateEnvironment18' },
  { emoji: Emojis.ClimateEnvironment19, name: 'ClimateEnvironment19' },
  { emoji: Emojis.ClimateEnvironment2, name: 'ClimateEnvironment2' },
  { emoji: Emojis.ClimateEnvironment20, name: 'ClimateEnvironment20' },
  { emoji: Emojis.ClimateEnvironment21, name: 'ClimateEnvironment21' },
  { emoji: Emojis.ClimateEnvironment22, name: 'ClimateEnvironment22' },
  { emoji: Emojis.ClimateEnvironment23, name: 'ClimateEnvironment23' },
  { emoji: Emojis.ClimateEnvironment24, name: 'ClimateEnvironment24' },
  { emoji: Emojis.ClimateEnvironment25, name: 'ClimateEnvironment25' },
  { emoji: Emojis.ClimateEnvironment26, name: 'ClimateEnvironment26' },
  { emoji: Emojis.ClimateEnvironment3, name: 'ClimateEnvironment3' },
  { emoji: Emojis.ClimateEnvironment4, name: 'ClimateEnvironment4' },
  { emoji: Emojis.ClimateEnvironment5, name: 'ClimateEnvironment5' },
  { emoji: Emojis.ClimateEnvironment6, name: 'ClimateEnvironment6' },
  { emoji: Emojis.ClimateEnvironment7, name: 'ClimateEnvironment7' },
  { emoji: Emojis.ClimateEnvironment8, name: 'ClimateEnvironment8' },
  { emoji: Emojis.ClimateEnvironment9, name: 'ClimateEnvironment9' },
];
  