/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/emergency';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Emergency1, name: 'Emergency1' },
  { emoji: Emojis.Emergency10, name: 'Emergency10' },
  { emoji: Emojis.Emergency11, name: 'Emergency11' },
  { emoji: Emojis.Emergency12, name: 'Emergency12' },
  { emoji: Emojis.Emergency13, name: 'Emergency13' },
  { emoji: Emojis.Emergency14, name: 'Emergency14' },
  { emoji: Emojis.Emergency15, name: 'Emergency15' },
  { emoji: Emojis.Emergency16, name: 'Emergency16' },
  { emoji: Emojis.Emergency17, name: 'Emergency17' },
  { emoji: Emojis.Emergency18, name: 'Emergency18' },
  { emoji: Emojis.Emergency19, name: 'Emergency19' },
  { emoji: Emojis.Emergency2, name: 'Emergency2' },
  { emoji: Emojis.Emergency20, name: 'Emergency20' },
  { emoji: Emojis.Emergency21, name: 'Emergency21' },
  { emoji: Emojis.Emergency22, name: 'Emergency22' },
  { emoji: Emojis.Emergency23, name: 'Emergency23' },
  { emoji: Emojis.Emergency24, name: 'Emergency24' },
  { emoji: Emojis.Emergency25, name: 'Emergency25' },
  { emoji: Emojis.Emergency26, name: 'Emergency26' },
  { emoji: Emojis.Emergency27, name: 'Emergency27' },
  { emoji: Emojis.Emergency28, name: 'Emergency28' },
  { emoji: Emojis.Emergency29, name: 'Emergency29' },
  { emoji: Emojis.Emergency3, name: 'Emergency3' },
  { emoji: Emojis.Emergency30, name: 'Emergency30' },
  { emoji: Emojis.Emergency31, name: 'Emergency31' },
  { emoji: Emojis.Emergency32, name: 'Emergency32' },
  { emoji: Emojis.Emergency33, name: 'Emergency33' },
  { emoji: Emojis.Emergency34, name: 'Emergency34' },
  { emoji: Emojis.Emergency35, name: 'Emergency35' },
  { emoji: Emojis.Emergency36, name: 'Emergency36' },
  { emoji: Emojis.Emergency37, name: 'Emergency37' },
  { emoji: Emojis.Emergency38, name: 'Emergency38' },
  { emoji: Emojis.Emergency39, name: 'Emergency39' },
  { emoji: Emojis.Emergency4, name: 'Emergency4' },
  { emoji: Emojis.Emergency40, name: 'Emergency40' },
  { emoji: Emojis.Emergency41, name: 'Emergency41' },
  { emoji: Emojis.Emergency42, name: 'Emergency42' },
  { emoji: Emojis.Emergency43, name: 'Emergency43' },
  { emoji: Emojis.Emergency44, name: 'Emergency44' },
  { emoji: Emojis.Emergency5, name: 'Emergency5' },
  { emoji: Emojis.Emergency6, name: 'Emergency6' },
  { emoji: Emojis.Emergency7, name: 'Emergency7' },
  { emoji: Emojis.Emergency8, name: 'Emergency8' },
  { emoji: Emojis.Emergency9, name: 'Emergency9' },
];
  