/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/flags';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Flags1, name: 'Flags1' },
  { emoji: Emojis.Flags10, name: 'Flags10' },
  { emoji: Emojis.Flags11, name: 'Flags11' },
  { emoji: Emojis.Flags12, name: 'Flags12' },
  { emoji: Emojis.Flags13, name: 'Flags13' },
  { emoji: Emojis.Flags14, name: 'Flags14' },
  { emoji: Emojis.Flags15, name: 'Flags15' },
  { emoji: Emojis.Flags16, name: 'Flags16' },
  { emoji: Emojis.Flags17, name: 'Flags17' },
  { emoji: Emojis.Flags18, name: 'Flags18' },
  { emoji: Emojis.Flags19, name: 'Flags19' },
  { emoji: Emojis.Flags2, name: 'Flags2' },
  { emoji: Emojis.Flags3, name: 'Flags3' },
  { emoji: Emojis.Flags4, name: 'Flags4' },
  { emoji: Emojis.Flags5, name: 'Flags5' },
  { emoji: Emojis.Flags6, name: 'Flags6' },
  { emoji: Emojis.Flags7, name: 'Flags7' },
  { emoji: Emojis.Flags8, name: 'Flags8' },
  { emoji: Emojis.Flags9, name: 'Flags9' },
];
  