/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../extras/food-drink';

export const EMOJI_LIST = [
  { emoji: Emojis.FoodDrink1, name: 'FoodDrink1' },
  { emoji: Emojis.FoodDrink2, name: 'FoodDrink2' },
  { emoji: Emojis.FoodDrink3, name: 'FoodDrink3' },
  { emoji: Emojis.FoodDrink4, name: 'FoodDrink4' },
  { emoji: Emojis.FoodDrink5, name: 'FoodDrink5' },
  { emoji: Emojis.FoodDrink6, name: 'FoodDrink6' },
  { emoji: Emojis.FoodDrink7, name: 'FoodDrink7' },
];
  