/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/gardening';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Gardening1, name: 'Gardening1' },
  { emoji: Emojis.Gardening2, name: 'Gardening2' },
  { emoji: Emojis.Gardening3, name: 'Gardening3' },
  { emoji: Emojis.Gardening4, name: 'Gardening4' },
  { emoji: Emojis.Gardening5, name: 'Gardening5' },
  { emoji: Emojis.Gardening6, name: 'Gardening6' },
  { emoji: Emojis.Gardening7, name: 'Gardening7' },
  { emoji: Emojis.Gardening8, name: 'Gardening8' },
  { emoji: Emojis.Gardening9, name: 'Gardening9' },
];
  