/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../extras/healthcare';

export const EMOJI_LIST = [
  { emoji: Emojis.Healthcare1, name: 'Healthcare1' },
  { emoji: Emojis.Healthcare10, name: 'Healthcare10' },
  { emoji: Emojis.Healthcare11, name: 'Healthcare11' },
  { emoji: Emojis.Healthcare12, name: 'Healthcare12' },
  { emoji: Emojis.Healthcare13, name: 'Healthcare13' },
  { emoji: Emojis.Healthcare14, name: 'Healthcare14' },
  { emoji: Emojis.Healthcare15, name: 'Healthcare15' },
  { emoji: Emojis.Healthcare16, name: 'Healthcare16' },
  { emoji: Emojis.Healthcare17, name: 'Healthcare17' },
  { emoji: Emojis.Healthcare18, name: 'Healthcare18' },
  { emoji: Emojis.Healthcare19, name: 'Healthcare19' },
  { emoji: Emojis.Healthcare2, name: 'Healthcare2' },
  { emoji: Emojis.Healthcare20, name: 'Healthcare20' },
  { emoji: Emojis.Healthcare21, name: 'Healthcare21' },
  { emoji: Emojis.Healthcare22, name: 'Healthcare22' },
  { emoji: Emojis.Healthcare23, name: 'Healthcare23' },
  { emoji: Emojis.Healthcare24, name: 'Healthcare24' },
  { emoji: Emojis.Healthcare25, name: 'Healthcare25' },
  { emoji: Emojis.Healthcare26, name: 'Healthcare26' },
  { emoji: Emojis.Healthcare27, name: 'Healthcare27' },
  { emoji: Emojis.Healthcare28, name: 'Healthcare28' },
  { emoji: Emojis.Healthcare29, name: 'Healthcare29' },
  { emoji: Emojis.Healthcare3, name: 'Healthcare3' },
  { emoji: Emojis.Healthcare30, name: 'Healthcare30' },
  { emoji: Emojis.Healthcare31, name: 'Healthcare31' },
  { emoji: Emojis.Healthcare32, name: 'Healthcare32' },
  { emoji: Emojis.Healthcare33, name: 'Healthcare33' },
  { emoji: Emojis.Healthcare34, name: 'Healthcare34' },
  { emoji: Emojis.Healthcare35, name: 'Healthcare35' },
  { emoji: Emojis.Healthcare36, name: 'Healthcare36' },
  { emoji: Emojis.Healthcare37, name: 'Healthcare37' },
  { emoji: Emojis.Healthcare38, name: 'Healthcare38' },
  { emoji: Emojis.Healthcare4, name: 'Healthcare4' },
  { emoji: Emojis.Healthcare5, name: 'Healthcare5' },
  { emoji: Emojis.Healthcare6, name: 'Healthcare6' },
  { emoji: Emojis.Healthcare7, name: 'Healthcare7' },
  { emoji: Emojis.Healthcare8, name: 'Healthcare8' },
  { emoji: Emojis.Healthcare9, name: 'Healthcare9' },
];
  