/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/interaction';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Interaction1, name: 'Interaction1' },
  { emoji: Emojis.Interaction10, name: 'Interaction10' },
  { emoji: Emojis.Interaction11, name: 'Interaction11' },
  { emoji: Emojis.Interaction12, name: 'Interaction12' },
  { emoji: Emojis.Interaction13, name: 'Interaction13' },
  { emoji: Emojis.Interaction14, name: 'Interaction14' },
  { emoji: Emojis.Interaction2, name: 'Interaction2' },
  { emoji: Emojis.Interaction3, name: 'Interaction3' },
  { emoji: Emojis.Interaction4, name: 'Interaction4' },
  { emoji: Emojis.Interaction5, name: 'Interaction5' },
  { emoji: Emojis.Interaction6, name: 'Interaction6' },
  { emoji: Emojis.Interaction7, name: 'Interaction7' },
  { emoji: Emojis.Interaction8, name: 'Interaction8' },
  { emoji: Emojis.Interaction9, name: 'Interaction9' },
];
  