/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/objects';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Objects1, name: 'Objects1' },
  { emoji: Emojis.Objects10, name: 'Objects10' },
  { emoji: Emojis.Objects11, name: 'Objects11' },
  { emoji: Emojis.Objects12, name: 'Objects12' },
  { emoji: Emojis.Objects13, name: 'Objects13' },
  { emoji: Emojis.Objects14, name: 'Objects14' },
  { emoji: Emojis.Objects15, name: 'Objects15' },
  { emoji: Emojis.Objects16, name: 'Objects16' },
  { emoji: Emojis.Objects2, name: 'Objects2' },
  { emoji: Emojis.Objects3, name: 'Objects3' },
  { emoji: Emojis.Objects4, name: 'Objects4' },
  { emoji: Emojis.Objects5, name: 'Objects5' },
  { emoji: Emojis.Objects6, name: 'Objects6' },
  { emoji: Emojis.Objects7, name: 'Objects7' },
  { emoji: Emojis.Objects8, name: 'Objects8' },
  { emoji: Emojis.Objects9, name: 'Objects9' },
];
  