/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../extras/people';

export const EMOJI_LIST = [
  { emoji: Emojis.People1, name: 'People1' },
  { emoji: Emojis.People2, name: 'People2' },
  { emoji: Emojis.People3, name: 'People3' },
  { emoji: Emojis.People4, name: 'People4' },
  { emoji: Emojis.People5, name: 'People5' },
  { emoji: Emojis.People6, name: 'People6' },
  { emoji: Emojis.People7, name: 'People7' },
  { emoji: Emojis.People8, name: 'People8' },
];
  