/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/smileys-emotion';
     
export const EMOJI_LIST = [
  { emoji: Emojis.SmileysEmotion1, name: 'SmileysEmotion1' },
  { emoji: Emojis.SmileysEmotion2, name: 'SmileysEmotion2' },
  { emoji: Emojis.SmileysEmotion3, name: 'SmileysEmotion3' },
];
  