/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/symbols';
     
export const EMOJI_LIST = [
  { emoji: Emojis.Symbols1, name: 'Symbols1' },
  { emoji: Emojis.Symbols2, name: 'Symbols2' },
];
  