/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../extras/technology';

export const EMOJI_LIST = [
  { emoji: Emojis.Technology1, name: 'Technology1' },
  { emoji: Emojis.Technology10, name: 'Technology10' },
  { emoji: Emojis.Technology11, name: 'Technology11' },
  { emoji: Emojis.Technology12, name: 'Technology12' },
  { emoji: Emojis.Technology13, name: 'Technology13' },
  { emoji: Emojis.Technology14, name: 'Technology14' },
  { emoji: Emojis.Technology15, name: 'Technology15' },
  { emoji: Emojis.Technology16, name: 'Technology16' },
  { emoji: Emojis.Technology17, name: 'Technology17' },
  { emoji: Emojis.Technology18, name: 'Technology18' },
  { emoji: Emojis.Technology19, name: 'Technology19' },
  { emoji: Emojis.Technology2, name: 'Technology2' },
  { emoji: Emojis.Technology20, name: 'Technology20' },
  { emoji: Emojis.Technology21, name: 'Technology21' },
  { emoji: Emojis.Technology22, name: 'Technology22' },
  { emoji: Emojis.Technology23, name: 'Technology23' },
  { emoji: Emojis.Technology3, name: 'Technology3' },
  { emoji: Emojis.Technology4, name: 'Technology4' },
  { emoji: Emojis.Technology5, name: 'Technology5' },
  { emoji: Emojis.Technology6, name: 'Technology6' },
  { emoji: Emojis.Technology7, name: 'Technology7' },
  { emoji: Emojis.Technology8, name: 'Technology8' },
  { emoji: Emojis.Technology9, name: 'Technology9' },
];
  