/**
 * Generated by scripts/generate-emojis.js.
 * DO NOT EDIT!
 */

import * as Emojis from '../../extras/travel-places';

export const EMOJI_LIST = [
  { emoji: Emojis.TravelPlaces1, name: 'TravelPlaces1' },
  { emoji: Emojis.TravelPlaces10, name: 'TravelPlaces10' },
  { emoji: Emojis.TravelPlaces11, name: 'TravelPlaces11' },
  { emoji: Emojis.TravelPlaces12, name: 'TravelPlaces12' },
  { emoji: Emojis.TravelPlaces13, name: 'TravelPlaces13' },
  { emoji: Emojis.TravelPlaces2, name: 'TravelPlaces2' },
  { emoji: Emojis.TravelPlaces3, name: 'TravelPlaces3' },
  { emoji: Emojis.TravelPlaces4, name: 'TravelPlaces4' },
  { emoji: Emojis.TravelPlaces5, name: 'TravelPlaces5' },
  { emoji: Emojis.TravelPlaces6, name: 'TravelPlaces6' },
  { emoji: Emojis.TravelPlaces7, name: 'TravelPlaces7' },
  { emoji: Emojis.TravelPlaces8, name: 'TravelPlaces8' },
  { emoji: Emojis.TravelPlaces9, name: 'TravelPlaces9' },
];
  