/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../extras/ui-element';
     
export const EMOJI_LIST = [
  { emoji: Emojis.UiElement10, name: 'UiElement10' },
  { emoji: Emojis.UiElement11, name: 'UiElement11' },
  { emoji: Emojis.UiElement12, name: 'UiElement12' },
  { emoji: Emojis.UiElement43, name: 'UiElement43' },
  { emoji: Emojis.UiElement44, name: 'UiElement44' },
  { emoji: Emojis.UiElement45, name: 'UiElement45' },
  { emoji: Emojis.UiElement46, name: 'UiElement46' },
  { emoji: Emojis.UiElement47, name: 'UiElement47' },
  { emoji: Emojis.UiElement48, name: 'UiElement48' },
  { emoji: Emojis.UiElement49, name: 'UiElement49' },
  { emoji: Emojis.UiElement5, name: 'UiElement5' },
  { emoji: Emojis.UiElement50, name: 'UiElement50' },
  { emoji: Emojis.UiElement51, name: 'UiElement51' },
  { emoji: Emojis.UiElement52, name: 'UiElement52' },
  { emoji: Emojis.UiElement53, name: 'UiElement53' },
  { emoji: Emojis.UiElement54, name: 'UiElement54' },
  { emoji: Emojis.UiElement55, name: 'UiElement55' },
  { emoji: Emojis.UiElement56, name: 'UiElement56' },
  { emoji: Emojis.UiElement57, name: 'UiElement57' },
  { emoji: Emojis.UiElement58, name: 'UiElement58' },
  { emoji: Emojis.UiElement59, name: 'UiElement59' },
  { emoji: Emojis.UiElement60, name: 'UiElement60' },
  { emoji: Emojis.UiElement61, name: 'UiElement61' },
  { emoji: Emojis.UiElement62, name: 'UiElement62' },
  { emoji: Emojis.UiElement63, name: 'UiElement63' },
  { emoji: Emojis.UiElement64, name: 'UiElement64' },
  { emoji: Emojis.UiElement65, name: 'UiElement65' },
  { emoji: Emojis.UiElement66, name: 'UiElement66' },
  { emoji: Emojis.UiElement67, name: 'UiElement67' },
  { emoji: Emojis.UiElement68, name: 'UiElement68' },
  { emoji: Emojis.UiElement69, name: 'UiElement69' },
  { emoji: Emojis.UiElement7, name: 'UiElement7' },
  { emoji: Emojis.UiElement70, name: 'UiElement70' },
  { emoji: Emojis.UiElement71, name: 'UiElement71' },
  { emoji: Emojis.UiElement72, name: 'UiElement72' },
  { emoji: Emojis.UiElement73, name: 'UiElement73' },
  { emoji: Emojis.UiElement74, name: 'UiElement74' },
  { emoji: Emojis.UiElement75, name: 'UiElement75' },
  { emoji: Emojis.UiElement76, name: 'UiElement76' },
  { emoji: Emojis.UiElement77, name: 'UiElement77' },
  { emoji: Emojis.UiElement78, name: 'UiElement78' },
  { emoji: Emojis.UiElement79, name: 'UiElement79' },
];
  