# Generated by scripts/generate-script.js
# DO NO EDIT

svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/activities/arts-crafts --ext tsx assets/activities/arts-crafts
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/activities/award-medal --ext tsx assets/activities/award-medal
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/activities/event --ext tsx assets/activities/event
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/activities/game --ext tsx assets/activities/game
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/activities/sport --ext tsx assets/activities/sport
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/animals-nature/animal-amphibian --ext tsx assets/animals-nature/animal-amphibian
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/animals-nature/animal-bird --ext tsx assets/animals-nature/animal-bird
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/animals-nature/animal-bug --ext tsx assets/animals-nature/animal-bug
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/animals-nature/animal-mammal --ext tsx assets/animals-nature/animal-mammal
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/animals-nature/animal-marine --ext tsx assets/animals-nature/animal-marine
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/animals-nature/animal-reptile --ext tsx assets/animals-nature/animal-reptile
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/animals-nature/plant-flower --ext tsx assets/animals-nature/plant-flower
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/animals-nature/plant-other --ext tsx assets/animals-nature/plant-other
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/animals-nature --ext tsx assets/extras/animals-nature
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/brand --ext tsx assets/extras/brand
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/climate-environment --ext tsx assets/extras/climate-environment
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/emergency --ext tsx assets/extras/emergency
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/flags --ext tsx assets/extras/flags
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/food-drink --ext tsx assets/extras/food-drink
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/gardening --ext tsx assets/extras/gardening
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/healthcare --ext tsx assets/extras/healthcare
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/interaction --ext tsx assets/extras/interaction
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/objects --ext tsx assets/extras/objects
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/people --ext tsx assets/extras/people
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/smileys-emotion --ext tsx assets/extras/smileys-emotion
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/symbols --ext tsx assets/extras/symbols
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/technology --ext tsx assets/extras/technology
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/travel-places --ext tsx assets/extras/travel-places
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/extras/ui-element --ext tsx assets/extras/ui-element
