# Generated by scripts/generate-script.js
# DO NO EDIT

svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/activities/arts-crafts --ext tsx assets/activities/arts-crafts
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/activities/award-medal --ext tsx assets/activities/award-medal
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/activities/event --ext tsx assets/activities/event
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/activities/game --ext tsx assets/activities/game
svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/activities/sport --ext tsx assets/activities/sport
