const fs = require('fs');

const generateScript = () => {
  const svgDir = './assets/';
  const saveDir = './scripts/';
  let scriptOutput = `# Generated by scripts/generate-script.js
# DO NO EDIT

`;
  
  // Read root Svg emoji directory
  fs.readdirSync(svgDir).forEach(folderName => {
    if (folderName === '.DS_Store') return;
    
    const subDir = `${svgDir}${folderName}`;
    
    // Read sub-directory
    return fs.readdirSync(subDir).forEach(subFolderName => {
      if (subFolderName === '.DS_Store') return;
      
      scriptOutput += `svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-color.js -d src/${folderName}/${subFolderName} --ext tsx assets/${folderName}/${subFolderName}
`;
    });
  });
  fs.writeFileSync(`${saveDir}all-scripts.sh`, scriptOutput);
};

generateScript();
