const fs = require("fs");
const path = require("path");

const generate = () => {
  const emojiDir = './assets/';
  // const saveDir = './src/';

  // Read root Emoji directory
  fs.readdirSync(emojiDir).forEach(fileName => {
    let emojiListOutput = '';
    let level1FileName = '';
    if (fileName === '.DS_Store') return;

    const level1Dir = `${emojiDir}${fileName}`;

    // Read level1-directory
    fs.readdirSync(level1Dir).forEach(_level1FileName => {
      if (_level1FileName === '.DS_Store') return;
      
      level1FileName = _level1FileName;
      const level2Dir = `${emojiDir}${fileName}/${_level1FileName}`;

      emojiListOutput = `/**
 * Generated by scripts/generate-logos.js.
 * DO NOT EDIT!
 */
     
import * as Emojis from '../../${fileName}/${_level1FileName}';
     
export const EMOJI_LIST = [
`;
      // Read level2-directory
      fs.readdirSync(level2Dir).forEach(level2FileName => {
        if (level2FileName === '.DS_Store') return;

       emojiListOutput += `  { emoji: Emojis.${level2FileName.split('.')[0]}, name: '${level2FileName.split('.')[0]}' },
`;
      });
      emojiListOutput += `];
  `;
     
       fs.writeFileSync(`./src/__stories__/${fileName}/${level1FileName}.ts`, emojiListOutput);
    });
  });
};

generate();
