export { default as PlaceMap1 } from './PlaceMap1'
export { default as PlaceMap2 } from './PlaceMap2'
export { default as PlaceMap3 } from './PlaceMap3'
export { default as PlaceMap4 } from './PlaceMap4'
export { default as PlaceMap5 } from './PlaceMap5'
export { default as PlaceMap6 } from './PlaceMap6'
export { default as PlaceMap7 } from './PlaceMap7'