name: Continuous Deployment

on:
  pull_request:
    types: closed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy Storybook
      run: |
        yarn
        CI=false yarn deploy-storybook --ci
